//--------------------------------------------------------
// ORMITPulserModel
// Created by Mark  A. Howe on Fri Jul 22 2005
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2005 CENPA, University of Washington. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//Washington at the Center for Experimental Nuclear Physics and 
//Astrophysics (CENPA) sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of Washington, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files

#import "ORAuxHw.h"

@class ORSerialPort;

@interface ORMITPulserModel : ORAuxHw
{
    @private
        NSString*        portName;
        BOOL             portWasOpen;
        ORSerialPort*    serialPort;
	
		int				pulserVersion;
		int				clockSpeed;
		int				resistance;
		int				dutyCycle;
		float			frequency;
}

#pragma mark ***Initialization
- (void) dealloc;

#pragma mark ***Accessors
- (float) frequency;
- (void) setFrequency:(float)aFrequency;
- (int) dutyCycle;
- (void) setDutyCycle:(int)aDutyCycle;
- (int) resistance;
- (void) setResistance:(int)aResistance;
- (int) clockSpeed;
- (void) setClockSpeed:(int)aClockSpeed;
- (int) pulserVersion;
- (void) setPulserVersion:(int)aPulserVersion;
- (ORSerialPort*) serialPort;
- (void) setSerialPort:(ORSerialPort*)aSerialPort;
- (BOOL) portWasOpen;
- (void) setPortWasOpen:(BOOL)aPortWasOpen;
- (NSString*) portName;
- (void) setPortName:(NSString*)aPortName;
- (void) openPort:(BOOL)state;
- (void) setPower:(BOOL)state;
- (float) actualClockSpeed;

#pragma mark ***Commands
- (void) loadHardware;
- (NSString*) clockCommand;
- (NSString*) resistanceCommand;
- (NSString*) dutyCycleCommand;
- (NSString*) frequencyCommand;

#pragma mark ***Archival
- (id)   initWithCoder:(NSCoder*)decoder;
- (void) encodeWithCoder:(NSCoder*)encoder;
@end

extern NSString* ORMITPulserModelFrequencyChanged;
extern NSString* ORMITPulserModelDutyCycleChanged;
extern NSString* ORMITPulserModelResistanceChanged;
extern NSString* ORMITPulserModelClockSpeedChanged;
extern NSString* ORMITPulserModelPulserVersionChanged;
extern NSString* ORMITPulserModelSerialPortChanged;
extern NSString* ORMITPulserLock;
extern NSString* ORMITPulserModelPortNameChanged;
extern NSString* ORMITPulserModelPortStateChanged;
