//--------------------------------------------------------
// ORMks660BController
// Created by Mark Howe on Wednesday, April 25, 2012
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2012 University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//North Carolina sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//North Carolina reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files

@class ORCompositePlotView;
@class ORSerialPortController;

@interface ORMks660BController : OrcaObjectController
{
    IBOutlet NSTextField*   lockDocField;
	IBOutlet NSTextField*	lowAlarmTextField;
	IBOutlet NSTextField*	highLimitTextField;
	IBOutlet NSTextField*	highAlarmTextField;
	IBOutlet NSTextField*	fullScaleRBTextField;
	IBOutlet NSTextField*	calibrationNumberTextField;
	IBOutlet NSTextField*	lowHysteresisTextField;
	IBOutlet NSTextField*	highHysteresisTextField;
	IBOutlet NSPopUpButton* decimalPtPositionPU;
	IBOutlet NSButton*		shipPressuresButton;
    IBOutlet NSButton*      lockButton;
    IBOutlet NSButton*		initHardwareButton;
    IBOutlet NSPopUpButton* pollTimePopup;
    IBOutlet NSButton*      readPressureButton;
    IBOutlet NSTextField*   pressureField;
    IBOutlet NSTextField*   timeField;
	IBOutlet ORCompositePlotView*    plotter0;

    IBOutlet NSMatrix*		lowSetPointMatrix;
    IBOutlet NSMatrix*		highSetPointMatrix;
    IBOutlet ORSerialPortController* serialPortController;
}

#pragma mark ***Initialization
- (id) init;
- (void) dealloc;
- (void) awakeFromNib;

#pragma mark ***Notifications
- (void) registerNotificationObservers;
- (void) updateWindow;

#pragma mark ***Interface Management
- (BOOL) portLocked;
- (void) setUpFormats;
- (void) lowAlarmChanged:(NSNotification*)aNote;
- (void) highLimitChanged:(NSNotification*)aNote;
- (void) highAlarmChanged:(NSNotification*)aNote;
- (void) fullScaleRBChanged:(NSNotification*)aNote;
- (void) calibrationNumberChanged:(NSNotification*)aNote;
- (void) lowHysteresisChanged:(NSNotification*)aNote;
- (void) highHysteresisChanged:(NSNotification*)aNote;
- (void) decimalPtPositionChanged:(NSNotification*)aNote;
- (void) updateTimePlot:(NSNotification*)aNote;
- (void) scaleAction:(NSNotification*)aNote;
- (void) shipPressuresChanged:(NSNotification*)aNote;
- (void) lowSetPointChanged:(NSNotification*)aNote;
- (void) highSetPointChanged:(NSNotification*)aNote;
- (void) lockChanged:(NSNotification*)aNote;
- (void) pressureChanged:(NSNotification*)aNote;
- (void) pollTimeChanged:(NSNotification*)aNote;
- (void) miscAttributesChanged:(NSNotification*)aNote;
- (void) scaleAction:(NSNotification*)aNote;
- (void) involvedInProcessChanged:(NSNotification*)aNote;

#pragma mark ***Actions
- (IBAction) lowAlarmAction:(id)sender;
- (IBAction) highLimitAction:(id)sender;
- (IBAction) highAlarmAction:(id)sender;
- (IBAction) calibrationNumberAction:(id)sender;
- (IBAction) lowHysteresisAction:(id)sender;
- (IBAction) highHysteresisAction:(id)sender;
- (IBAction) decimalPtPositionAction:(id)sender;
- (IBAction) initHardwareAction:(id)sender;
- (IBAction) readHardware:(id)sender;
- (IBAction) shipPressuresAction:(id)sender;
- (IBAction) lockAction:(id) sender;
- (IBAction) readPressureAction:(id)sender;
- (IBAction) pollTimeAction:(id)sender;
- (IBAction) lowSetPointAction:(id)sender;
- (IBAction) highSetPointAction:(id)sender;
- (IBAction) pollNowAction:(id)sender;
- (IBAction) loadDialogFromHW:(id)sender;
- (IBAction) zeroAction:(id)sender;
- (IBAction) fullScaleAction:(id)sender;

#if !defined(MAC_OS_X_VERSION_10_10) && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_10 // 10.10-specific
- (void) fullScaleDidFinish:(id)sheet returnCode:(int)returnCode contextInfo:(NSDictionary*)userInfo;
- (void) zeroDidFinish:(id)sheet returnCode:(int)returnCode contextInfo:(NSDictionary*)userInfo;
- (void) loadDialogDidFinish:(id)sheet returnCode:(int)returnCode contextInfo:(NSDictionary*)userInfo;
#endif
- (int) numberPointsInPlot:(id)aPlotter;
- (void) plotter:(id)aPlotter index:(int)i x:(double*)xValue y:(double*)yValue;

@end


