//--------------------------------------------------------
// ORADEIControlDefs.h
// Created by A. Kopmann on Feb 8, 2019
// Copyright (c) 2019, University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of
//North Carolina sponsored in part by the United States
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020.
//The University has certain rights in the program pursuant to
//the contract and the program should not be copied or distributed
//outside your organization.  The DOE and the University of
//North Carolina reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty,
//express or implied, or assume any liability or responsibility
//for the use of this software.
//-------------------------------------------------------------


// Static definition of setpoints

//
// 113-RS e-gun cRIO
//

static NSString* setPointList_RS1[] = {
    @"-", @"Timestamp 1 [Egun_cRIO Timestamps (SOLL) ]",
    @"-", @"Timestamp 2 [Egun_cRIO Timestamps (SOLL) ]",
    @"113-ELV-1-0101-0100", @"[voltage] Booster Coil Rear Voltage     [Magnet System SOLL]",
    @"113-ELV-1-0101-0101", @"[current] Booster Coil Rear Current     [Magnet System SOLL]",
    @"113-ELV-1-0201-0100", @"[voltage] Booster Coil Front Voltage     [Magnet System SOLL]",
    @"113-ELV-1-0201-0101", @"[current] Booster Coil Front Current     [Magnet System SOLL]",
    @"113-ELV-1-0301-0100", @"[voltage] Solenoid Rear Voltage     [Magnet System SOLL]",
    @"113-ELV-1-0301-0101", @"[current] Solenoid Rear Current     [Magnet System SOLL]",
    @"113-ELV-1-0401-0100", @"[voltage] Solenoid Middle Voltage     [Magnet System SOLL]",
    @"113-ELV-1-0401-0101", @"[current] Solenoid Middle Current     [Magnet System SOLL]",
    @"113-ELV-1-0501-0100", @"[voltage] Solenoid Front Voltage     [Magnet System SOLL]",
    @"113-ELV-1-0501-0101", @"[current] Solenoid Front Current     [Magnet System SOLL]",
    @"113-ELV-1-0601-0100", @"[voltage] Steering Coil X voltage     [Magnet System SOLL]",
    @"113-ELV-1-0601-0101", @"[current] Steering Coil X current     [Magnet System SOLL]",
    @"113-ELV-1-0601-0103", @"[frequency] Steering Coil X frequency     [Magnet System SOLL]",
    @"113-ELV-1-0601-0104", @"[mode] Steering Coil X amplitude     [Magnet System SOLL]",
    @"113-ELV-1-0601-0105", @"[mode] Steering Coil X mode     [Magnet System SOLL]",
    @"113-ELV-1-0602-0100", @"[voltage] Steering Coil Y voltage     [Magnet System SOLL]",
    @"113-ELV-1-0602-0101", @"[current] Steering Coil Y current     [Magnet System SOLL]",
    @"113-ELV-1-0602-0103", @"[frequency] Steering Coil Y frequency     [Magnet System SOLL]",
    @"113-ELV-1-0602-0104", @"[mode] Steering Coil Y amplitude     [Magnet System SOLL]",
    @"113-ELV-1-0602-0105", @"[mode] Steering Coil Y mode     [Magnet System SOLL]",
    @"113-ELV-1-0603-0100", @"[voltage] Compensation Coil X voltage     [Magnet System SOLL]",
    @"113-ELV-1-0603-0101", @"[current] Compensation Coil X current     [Magnet System SOLL]",
    @"113-ELV-1-0603-0103", @"[frequency] Compensation Coil X frequency     [Magnet System SOLL]",
    @"113-ELV-1-0603-0104", @"[mode] Compensation Coil X amplitude     [Magnet System SOLL]",
    @"113-ELV-1-0603-0105", @"[mode] Compensation Coil X mode     [Magnet System SOLL]",
    @"113-ELV-1-0604-0100", @"[voltage] Compensation Coil Y voltage     [Magnet System SOLL]",
    @"113-ELV-1-0604-0101", @"[current] Compensation Coil Y current     [Magnet System SOLL]",
    @"113-ELV-1-0604-0103", @"[frequency] Compensation Coil Y frequency     [Magnet System SOLL]",
    @"113-ELV-1-0604-0104", @"[mode] Compensation Coil Y amplitude     [Magnet System SOLL]",
    @"113-ELV-1-0604-0105", @"[mode] Compensation Coil Y mode     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved     [Magnet System SOLL]",
    @"-", @"Reserved [Magnet System SOLL]",
    @"111-EHV-0-1101-0100", @"[voltage] Emission electrode Voltage     [High Voltage SOLL]",
    @"111-EHV-0-1101-0101", @"[current/micro] Emission electrode Current     [High Voltage SOLL]",
    @"111-EHV-0-1102-0100", @"[voltage] Acceleration electrode Voltage     [High Voltage SOLL]",
    @"111-EHV-0-1102-0101", @"[current/micro] Acceleration electrode Current     [High Voltage SOLL]",
    @"111-EHV-0-1100-0100", @"[voltage] Electrode difference Voltage     [High Voltage SOLL]",
    @"111-REU-0-1201-0100", @"[voltage] Emission electrode DVM Voltage Range     [High Voltage SOLL]",
    @"-", @"Stahl HV Chn 1 Reserved     [High Voltage SOLL]",
    @"-", @"Stahl HV Chn 2 Reserved     [High Voltage SOLL]",
    @"110-EHV-0-3101-0102", @"[voltage] Rear wall Stahl HV Voltage     [High Voltage SOLL]",
    @"110-EHV-0-3101-0100", @"[voltage] RW Bias High Voltage     [High Voltage SOLL]",
    @"110-EHV-0-3101-0101", @"[current] RW Bias High Current     [High Voltage SOLL]",
    @"110-EHV-0-3102-0100", @"[voltage] RW Bias Low Voltage     [High Voltage SOLL]",
    @"110-EHV-0-3102-0101", @"[voltage] RW Bias Low Offset     [High Voltage SOLL]",
    @"110-EHV-0-3102-0102", @"[frequency] RW Bias Low Frequency     [High Voltage SOLL]",
    @"111-EHV-1-1101-0105", @"[time] Iseg Ramp length     [High Voltage SOLL]",
    @"111-EHV-1-1101-0106", @"[voltage] Iseg Ramp Start value     [High Voltage SOLL]",
    @"111-EHV-1-1101-0107", @"[voltage] Iseg Ramp Stop value     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved     [High Voltage SOLL]",
    @"-", @"Reserved [High Voltage SOLL]",
    @"111-RTY-0-2102-0100", @"[temperature] LDLS Temperature Controller Temperature     [Optic System SOLL]",
    @"111-LFI-0-2103-0100", @"[wafelength/nano] Monochromator Wavelegth     [Optic System SOLL]",
    @"111-LFI-0-2103-0101", @"[width/nano] Monochromator Spectral Resolution     [Optic System SOLL]",
    @"111-REI-0-2401-0100", @"[number] Beam Monitor Amplifier Amplification coeficient     [Optic System SOLL]",
    @"111-REI-0-2401-0103", @"[number] Beam Monitor Reserved     [Optic System SOLL]",
    @"111-LUV-0-2501-0103", @"[frequency/kilo] UV Laser Pulse Frequency     [Optic System SOLL]",
    @"111-LUV-0-2501-0104", @"[current] UV Laser diode operating current     [Optic System SOLL]",
    @"111-CPS-0-2502-0101", @"[frequency/kilo] Pulser frequency     [Optic System SOLL]",
    @"111-CPS-0-2502-0102", @"[voltage] Pulser amplitude     [Optic System SOLL]",
    @"111-CPS-0-2502-0103", @"[time/nano] Pulser pulse length     [Optic System SOLL]",
    @"-", @"RW Illumination Reserved     [Optic System SOLL]",
    @"-", @"RW Illumination Reserved     [Optic System SOLL]",
    @"-", @"RW Illumination Reserved     [Optic System SOLL]",
    @"-", @"RW Illumination Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved     [Optic System SOLL]",
    @"-", @"Reserved [Optic System SOLL]",
    @"111-LUV-0-2101-0100", @"[bit] LDLS ON/OFF     [Optic System Control Word 1]",
    @"111-REI-0-2401-0102", @"[bit] Beam Monitor Amplifier Coupling     [Optic System Control Word 1]",
    @"111-REI-0-2401-0101", @"[bit] Beam Monitor Amplifier Hi/Low Speed     [Optic System Control Word 1]",
    @"111-LUV-0-2501-0108", @"[status] UV Laser Shutter open/close     [Optic System Control Word 1]",
    @"111-LUV-0-2501-0101", @"[status] UV Laser diode standby ON-OFF     [Optic System Control Word 1]",
    @"111-LUV-0-2501-0102", @"[status] UV Laser Trigger Mode Int/Ext     [Optic System Control Word 1]",
    @"113-ELV-1-0500-0100", @"[set] TDK Set     [Optic System Control Word 1]",
    @"113-ELV-1-0600-0100", @"[set] CAENels reserved     [Optic System Control Word 1]",
    @"111-EHV-1-1101-0102", @"[set] ISEG 500V Set     [Optic System Control Word 1]",
    @"111-EHV-1-1102-0102", @"[set] ISEG 6kV Set     [Optic System Control Word 1]",
    @"111-EHV-0-1100-0101", @"[set] ISEG Set     [Optic System Control Word 1]",
    @"111-AAI-0-3101-0101", @"[set]  Plate Angle Motor Start     [Optic System Control Word 1]",
    @"111-RTY-0-2102-0101", @"[set] LDLS Temperature Controller ON-OFF     [Optic System Control Word 1]",
    @"111-EHV-1-1101-0103", @"[set] Iseg Ramp Set     [Optic System Control Word 1]",
    @"111-EHV-1-1101-0104", @"[set] Iseg Ramp Abort     [Optic System Control Word 1]",
    @"111-LUV-0-2501-0105", @"[set] Clear Laser Interlock [Optic System Control Word 1]",
    @"111-LUV-0-2101-0101", @"[set] Clear LDLS Interlock     [Optic System Control Word 2]",
    @"113-ELV-1-0601-0105", @"[bit] Set Steering Coil X     [Optic System Control Word 2]",
    @"113-ELV-1-0602-0105", @"[bit] Set Steering Coil Y     [Optic System Control Word 2]",
    @"113-ELV-1-0603-0105", @"[bit] Set Compensation Coil X     [Optic System Control Word 2]",
    @"113-ELV-1-0604-0105", @"[bit] Set Compensation Coil Y     [Optic System Control Word 2]",
    @"-", @"Reserved     [Optic System Control Word 2]",
    @"-", @"Reserved     [Optic System Control Word 2]",
    @"-", @"Reserved     [Optic System Control Word 2]",
    @"-", @"Reserved     [Optic System Control Word 2]",
    @"-", @"Reserved     [Optic System Control Word 2]",
    @"-", @"Reserved     [Optic System Control Word 2]",
    @"-", @"Reserved     [Optic System Control Word 2]",
    @"-", @"Reserved     [Optic System Control Word 2]",
    @"-", @"Reserved     [Optic System Control Word 2]",
    @"-", @"Reserved     [Optic System Control Word 2]",
    @"-", @"Reserved [Optic System Control Word 2]",
    @"111-AAI-0-3101-0100", @"[degree] Egun Plate Angle     [RS Egun SOLL]",
    @"-", @"Reserved     [RS Egun SOLL]",
    @"-", @"Reserved     [RS Egun SOLL]",
    @"-", @"Reserved     [RS Egun SOLL]",
    @"-", @"Reserved     [RS Egun SOLL]",
    @"-", @"Reserved     [RS Egun SOLL]",
    @"-", @"Reserved     [RS Egun SOLL]",
    @"-", @"Reserved     [RS Egun SOLL]",
    @"-", @"Reserved     [RS Egun SOLL]",
    @"-", @"Reserved [RS Egun SOLL]",
    @"200-ELV-5-3410-0020", @"[status] Rampe einschalten / ausschalten1     [WGTS Dipole PS SOLL]",
    @"200-ELV-5-3410-0021", @"[status] Polung negativ / positiv1     [WGTS Dipole PS SOLL]",
    @"200-ELV-5-3420-0022", @"[status] Rampe einschalten / ausschalten2     [WGTS Dipole PS SOLL]",
    @"200-ELV-5-3420-0023", @"[status] Polung negativ / positiv2     [WGTS Dipole PS SOLL]",
    @"200-ELV-5-3410-0024", @"[current] Zielsollwert1     [WGTS Dipole PS SOLL]",
    @"200-ELV-5-3410-0025", @"[rate] Rampengeschwindigkeit Up1     [WGTS Dipole PS SOLL]",
    @"200-ELV-5-3410-0026", @"[rate] Rampengeschwindigkeit Down1     [WGTS Dipole PS SOLL]",
    @"200-ELV-5-3420-0027", @"[current] Zielsollwert2     [WGTS Dipole PS SOLL]",
    @"200-ELV-5-3420-0028", @"[rate] Rampengeschwindigkeit Up2     [WGTS Dipole PS SOLL]",
    @"200-ELV-5-3420-0029", @"[rate] Rampengeschwindigkeit Down2   [WGTS Dipole PS SOLL]",
    @"", @""
};

static NSString* measuredValueList_RS1[] = {
    @"-", @"Timestamp 1",
    @"-", @"Timestamp 2",
    @"113-ELV-1-0101-0000", @"[voltage] Booster Coil Rear Voltage     [EgunRS Magnet System IST]",
    @"113-ELV-1-0101-0001", @"[current] Booster Coil Rear Current     [EgunRS Magnet System IST]",
    @"113-ELV-1-0101-0002", @"[status] Booster Coil Rear Status     [EgunRS Magnet System IST]",
    @"113-ELV-1-0201-0000", @"[voltage] Booster Coil Front Voltage     [EgunRS Magnet System IST]",
    @"113-ELV-1-0201-0001", @"[current] Booster Coil Front Current     [EgunRS Magnet System IST]",
    @"113-ELV-1-0201-0002", @"[status] Booster Coil Front Status     [EgunRS Magnet System IST]",
    @"113-ELV-1-0301-0000", @"[voltage] Solenoid Rear Voltage     [EgunRS Magnet System IST]",
    @"113-ELV-1-0301-0001", @"[current] Solenoid Rear Current     [EgunRS Magnet System IST]",
    @"113-ELV-1-0301-0002", @"[status] Solenoid Rear Status     [EgunRS Magnet System IST]",
    @"113-ELV-1-0401-0000", @"[voltage] Solenoid Middle Voltage     [EgunRS Magnet System IST]",
    @"113-ELV-1-0401-0001", @"[current] Solenoid Middle Current     [EgunRS Magnet System IST]",
    @"113-ELV-1-0401-0002", @"[status] Solenoid Middle Status     [EgunRS Magnet System IST]",
    @"113-ELV-1-0501-0000", @"[voltage] Solenoid Front Voltage     [EgunRS Magnet System IST]",
    @"113-ELV-1-0501-0001", @"[current] Solenoid Front Current     [EgunRS Magnet System IST]",
    @"113-ELV-1-0501-0002", @"[status] Solenoid Front Status     [EgunRS Magnet System IST]",
    @"113-ELV-1-0601-0000", @"[voltage] Steering Coil X voltage     [EgunRS Magnet System IST]",
    @"113-ELV-1-0601-0001", @"[current] Steering Coil X current     [EgunRS Magnet System IST]",
    @"113-ELV-1-0601-0002", @"[status] Steering Coil X status     [EgunRS Magnet System IST]",
    @"113-ELV-1-0601-0003", @"[frequency] Steering Coil X frequency     [EgunRS Magnet System IST]",
    @"113-ELV-1-0601-0004", @"[current] Steering Coil X amplitude     [EgunRS Magnet System IST]",
    @"113-ELV-1-0601-0006", @"[watt] Steering Coil X power     [EgunRS Magnet System IST]",
    @"113-ELV-1-0601-0005", @"[mode] Steering Coil X mode     [EgunRS Magnet System IST]",
    @"113-ELV-1-0601-0007", @"[temperature] Steering Coil X Power Supply temperature 1     [EgunRS Magnet System IST]",
    @"113-ELV-1-0601-0008", @"[temperature] Steering Coil X Power Supply temperature 2     [EgunRS Magnet System IST]",
    @"113-ELV-1-0602-0000", @"[voltage] Steering Coil Y voltage     [EgunRS Magnet System IST]",
    @"113-ELV-1-0602-0001", @"[current] Steering Coil Y current     [EgunRS Magnet System IST]",
    @"113-ELV-1-0602-0002", @"[status] Steering Coil Y status     [EgunRS Magnet System IST]",
    @"113-ELV-1-0602-0003", @"[frequency] Steering Coil Y frequency     [EgunRS Magnet System IST]",
    @"113-ELV-1-0602-0004", @"[current] Steering Coil Y amplitude     [EgunRS Magnet System IST]",
    @"113-ELV-1-0602-0006", @"[watt] Steering Coil Y power     [EgunRS Magnet System IST]",
    @"113-ELV-1-0602-0005", @"[mode] Steering Coil Y mode     [EgunRS Magnet System IST]",
    @"113-ELV-1-0602-0007", @"[temperature] Steering Coil Y Power Supply temperature 1     [EgunRS Magnet System IST]",
    @"113-ELV-1-0602-0008", @"[temperature] Steering Coil Y Power Supply temperature 2     [EgunRS Magnet System IST]",
    @"113-ELV-1-0603-0000", @"[voltage] Compensation Coil X voltage     [EgunRS Magnet System IST]",
    @"113-ELV-1-0603-0001", @"[current] Compensation Coil X current     [EgunRS Magnet System IST]",
    @"113-ELV-1-0603-0002", @"[status] Compensation Coil X status     [EgunRS Magnet System IST]",
    @"113-ELV-1-0603-0003", @"[frequency] Compensation Coil X frequency     [EgunRS Magnet System IST]",
    @"113-ELV-1-0603-0004", @"[current] Compensation Coil X amplitude     [EgunRS Magnet System IST]",
    @"113-ELV-1-0603-0006", @"[watt] Compensation Coil X power     [EgunRS Magnet System IST]",
    @"113-ELV-1-0603-0005", @"[mode] Compensation Coil X mode     [EgunRS Magnet System IST]",
    @"113-ELV-1-0603-0007", @"[temperature] Compensation Coil X Power Supply temperature 1     [EgunRS Magnet System IST]",
    @"113-ELV-1-0603-0008", @"[temperature] Compensation Coil X Power Supply temperature 2     [EgunRS Magnet System IST]",
    @"113-ELV-1-0604-0000", @"[voltage] Compensation Coil Y voltage     [EgunRS Magnet System IST]",
    @"113-ELV-1-0604-0001", @"[current] Compensation Coil Y current     [EgunRS Magnet System IST]",
    @"113-ELV-1-0604-0002", @"[status] Compensation Coil Y status     [EgunRS Magnet System IST]",
    @"113-ELV-1-0604-0003", @"[frequency] Compensation Coil Y frequency     [EgunRS Magnet System IST]",
    @"113-ELV-1-0604-0004", @"[current] Compensation Coil Y amplitude     [EgunRS Magnet System IST]",
    @"113-ELV-1-0604-0006", @"[watt] Compensation Coil Y power     [EgunRS Magnet System IST]",
    @"113-ELV-1-0604-0005", @"[mode] Compensation Coil Y mode     [EgunRS Magnet System IST]",
    @"113-ELV-1-0604-0007", @"[temperature] Compensation Coil Y Power Supply temperature 1     [EgunRS Magnet System IST]",
    @"113-ELV-1-0604-0008", @"[temperature] Compensation Coil Y Power Supply temperature 2     [EgunRS Magnet System IST]",
    @"113-RTP-1-0111-0000", @"[temperature] Booster Coil Rear Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0121-0000", @"[temperature] Booster Coil Rear Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0211-0000", @"[temperature] Booster Coil Front Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0221-0000", @"[temperature] Booster Coil Front Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0311-0000", @"[temperature] Solenoid Rear Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0321-0000", @"[temperature] Solenoid Rear Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0411-0000", @"[temperature] Solenoid Middle Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0421-0000", @"[temperature] Solenoid Middle Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0511-0000", @"[temperature] Solenoid Front Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0521-0000", @"[temperature] Solenoid Front Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0611-0000", @"[temperature] Steering Coil X Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0621-0000", @"[temperature] Steering Coil X Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0612-0000", @"[temperature] Steering Coil Y Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0622-0000", @"[temperature] Steering Coil Y Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0613-0000", @"[temperature] Compensation Coil X Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0623-0000", @"[temperature] Compensation Coil X Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0614-0000", @"[temperature] Compensation Coil Y Temperature     [EgunRS Magnet System IST]",
    @"113-RTP-1-0624-0000", @"[temperature] Compensation Coil Y Temperature     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved     [EgunRS Magnet System IST]",
    @"-", @"Reserved [EgunRS Magnet System IST]",
    @"111-EHV-0-1101-0000", @"[polarity] Emission electrode Polarity     [High Voltage IST]",
    @"111-EHV-0-1101-0001", @"[voltage] Emission electrode Voltage     [High Voltage IST]",
    @"111-EHV-0-1101-0002", @"[current/micro] Emission electrode Current     [High Voltage IST]",
    @"111-EHV-0-1101-0003", @"[status] Emission electrode Status     [High Voltage IST]",
    @"111-EHV-0-1102-0000", @"[polarity] Acceleration electrode Polarity     [High Voltage IST]",
    @"111-EHV-0-1102-0001", @"[voltage] Acceleration electrode Voltage     [High Voltage IST]",
    @"111-EHV-0-1102-0002", @"[current/micro] Acceleration electrode Current     [High Voltage IST]",
    @"111-EHV-0-1102-0003", @"[status] Acceleration electrode Status     [High Voltage IST]",
    @"111-EHV-0-1100-0000", @"[voltage] Electrode difference Voltage     [High Voltage IST]",
    @"111-EHV-0-1100-0001", @"[status] ISEG MMC Status     [High Voltage IST]",
    @"111-REU-0-1201-0000", @"[voltage] Emission electrode DVM Voltage     [High Voltage IST]",
    @"111-REU-0-1201-0001", @"[status] Emission electrode DVM Status     [High Voltage IST]",
    @"111-EHV-0-1301-0000", @"[voltage] Stahl HV Channel 1 Voltage     [High Voltage IST]",
    @"111-EHV-0-1301-0001", @"[status]  Stahl HV Channel 1 Status     [High Voltage IST]",
    @"-", @" Stahl HV Chn 1 Reserved     [High Voltage IST]",
    @"-", @" Stahl HV Chn 2 Reserved     [High Voltage IST]",
    @"110-EHV-0-3101-0004", @"[voltage] Rear wall Stahl HV  Voltage     [High Voltage IST]",
    @"110-EHV-0-3101-0005", @"[current/micro] Rear wall  Stah HV Current     [High Voltage IST]",
    @"110-EHV-0-3101-0006", @"[status] Rear wall Stahl HV Status     [High Voltage IST]",
    @"110-EHV-0-3101-0000", @"[voltage] RW Bias High Voltage     [High Voltage IST]",
    @"110-EHV-0-3101-0001", @"[status] RW Bias High Status     [High Voltage IST]",
    @"110-EHV-0-3101-0002", @"[current] RW Bias High Current     [High Voltage IST]",
    @"110-EHV-0-3101-0003", @"[polarity] RW Bias High Polarity     [High Voltage IST]",
    @"110-EHV-0-3102-0000", @"[voltage] RW Bias Low  Voltage     [High Voltage IST]",
    @"110-EHV-0-3101-0001", @"[voltage] RW Bias Low Offset     [High Voltage IST]",
    @"110-EHV-0-3101-0002", @"[frequency] RW Bias Low Frequency     [High Voltage IST]",
    @"110-EHV-0-3101-0003", @"[status] RW Bias Low Status     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved     [High Voltage IST]",
    @"-", @"Reserved   [High Voltage IST]",
    @"111-LUV-0-2101-0000", @"[status] LDLS External Interlock [Optic System Status Word]",
    @"111-LUV-0-2101-0001", @"[status] LDLS LAMP ON [Optic System Status Word]",
    @"111-LUV-0-2101-0002", @"[status] LDLS Laser ON [Optic System Status Word]",
    @"111-LUV-0-2101-0003", @"[status] LDLS LAMP module fault [Optic System Status Word]",
    @"111-LUV-0-2101-0004", @"[status] LDLS Controller fault [Optic System Status Word]",
    @"111-LUV-0-2501-0000", @"[status] UV Laser diode status [Optic System Status Word]",
    @"111-LUV-0-2501-0001", @"[status] UV Laser diode standby ON-OFF status [Optic System Status Word]",
    @"111-LUV-0-2501-0002", @"[status] UV Laser Trigger Mode Int/Ext [Optic System Status Word]",
    @"111-CPS-0-2502-0000", @"[status] Pulser status [Optic System Status Word]",
    @"111-RTY-0-2102-0004", @"[status] LDLS Temperature Controller ON-OFF? [Optic System Status Word]",
    @"-", @"Reserved [Optic System Status Word]",
    @"-", @"Reserved [Optic System Status Word]",
    @"-", @"Reserved [Optic System Status Word]",
    @"-", @"Reserved [Optic System Status Word]",
    @"-", @"Reserved [Optic System Status Word]",
    @"-", @"ORCA-ZEUS Master bit [Optic System Status Word]",
    @"111-RTY-0-2102-0000", @"[temperature] LDLS Temperature Controller Temperature     [Optic System IST]",
    @"111-RTY-0-2102-0001", @"[voltage] LDLS Temperature Controller Voltage     [Optic System IST]",
    @"111-RTY-0-2102-0002", @"[current] LDLS Temperature Controller Current     [Optic System IST]",
    @"111-RTY-0-2102-0003", @"[status] LDLS Temperature Controller Status     [Optic System IST]",
    @"111-LFI-0-2103-0000", @"[wafelength/nano] Monochromator Wavelegth     [Optic System IST]",
    @"111-LFI-0-2103-0001", @"[width/micro] Monochromator Entrance Slit Width     [Optic System IST]",
    @"111-LFI-0-2103-0002", @"[width/micro] Monochromator Exit Slit Width     [Optic System IST]",
    @"111-LFI-0-2103-0003", @"[status] Monochromator Status     [Optic System IST]",
    @"111-REI-0-2401-0000", @"[status] Beam Monitor Amplifier Overload     [Optic System IST]",
    @"111-REU-0-2402-0001", @"[voltage] Beam Monitor Readout     [Optic System IST]",
    @"111-RTY-0-2403-0000", @"[temperature] Beam Monitor Reserved      [Optic System IST]",
    @"111-RTY-0-2403-0001", @"[temperature] Beam Monitor Reserved      [Optic System IST]",
    @"111-RTY-0-2403-0002", @"[temperature] Beam Monitor Reserved      [Optic System IST]",
    @"111-RTY-0-2403-0003", @"[temperature] Beam Monitor Reserved      [Optic System IST]",
    @"111-LUV-0-2501-0003", @"[frequency/kilo] UV Laser Pulse Frequency     [Optic System IST]",
    @"111-LUV-0-2501-0004", @"[current] UV Laser diode operating current     [Optic System IST]",
    @"111-LUV-0-2501-0005", @"[temperature] UV Laser SHG crystal temperature     [Optic System IST]",
    @"111-LUV-0-2501-0006", @"[temperature] UV Laser FHG crystal temperature     [Optic System IST]",
    @"111-LUV-0-2501-0007", @"[temperature] UV Laser diode 1 temperature     [Optic System IST]",
    @"111-CPS-0-2502-0001", @"[frequency/kilo] Pulser frequency     [Optic System IST]",
    @"111-CPS-0-2502-0002", @"[voltage] Pulser amplitude     [Optic System IST]",
    @"111-CPS-0-2502-0003", @"[time/nano] Pulser pulse length     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"RW Illumination Reserved     [Optic System IST]",
    @"-", @"Reserved     [Optic System IST]",
    @"-", @"Reserved     [Optic System IST]",
    @"-", @"Reserved     [Optic System IST]",
    @"-", @"Reserved     [Optic System IST]",
    @"-", @"Reserved     [Optic System IST]",
    @"-", @"Reserved [Optic System IST]",
    @"111-AAI-0-3101-0000", @"[mm] Linear Screw Drive position     [RSEgun IST]",
    @"111-AAI-0-3101-0001", @"[status] Linear Screw Drive status     [RSEgun IST]",
    @"111-AAI-0-3101-0002", @"[degree] Egun plate angle     [RSEgun IST]",
    @"111-AAI-0-3101-0003", @"[mm] Linear Feedthrough reserved     [RSEgun IST]",
    @"111-AAI-0-3101-0004", @"[status] Linear Screw Drive End-Switches status     [RSEgun IST]",
    @"-", @"Reserved     [RSEgun IST]",
    @"-", @"Reserved     [RSEgun IST]",
    @"-", @"Reserved     [RSEgun IST]",
    @"-", @"Reserved     [RSEgun IST]",
    @"-", @"Reserved [RSEgun IST]",
    @"200-ELV-5-3410-0000", @"[status] Automatikmodus Rampe1 [Dipole PS IST]",
    @"200-ELV-5-3410-0001", @"[status] Automatikmodus Polung1 [Dipole PS IST]",
    @"200-ELV-5-3410-0002", @"[status] Rueckmeldung Polung1 [Dipole PS IST]",
    @"200-ELV-5-3420-0003", @"[status] Automatikmodus Rampe2 [Dipole PS IST]",
    @"200-ELV-5-3420-0004", @"[status] Automatikmodus Polung2 [Dipole PS IST]",
    @"200-ELV-5-3420-0005", @"[status] Rueckmeldung Polung2 [Dipole PS IST]",
    @"200-ELV-5-3410-0006", @"[current] Zielsollwert1 [Dipole PS IST]",
    @"200-ELV-5-3410-0007", @"[rate] Rampengeschwindigkeit Up1 [Dipole PS IST]",
    @"200-ELV-5-3410-0008", @"[rate] Rampengeschwindigkeit Down1 [Dipole PS IST]",
    @"200-ELV-5-3410-0009", @"[current] Istwert1 [Dipole PS IST]",
    @"200-ELV-5-3420-0010", @"[current] Zielsollwert2 [Dipole PS IST]",
    @"200-ELV-5-3420-0011", @"[rate] Rampengeschwindigkeit Up2 [Dipole PS IST]",
    @"200-ELV-5-3420-0012", @"[rate] Rampengeschwindigkeit Down2 [Dipole PS IST]",
    @"200-ELV-5-3420-0013", @"[current] Istwert2 [Dipole PS IST]",
    @"", @""
};


#define kNumToShip_RS1  0 //
static NSString* itemsToShip_RS1[kNumToShip_RS1*2] = {
/*
    @"38",  @"436-EHV-0-1001-0001-U_set",
    @"39",  @"436-EHV-0-1001-0002-U_act",
    @"40",  @"436-EHV-0-1001-0003-I_max",
    @"41",  @"436-EHV-0-1001-0004-I_act",
    @"42",  @"436-EHV-0-1001-0005-U_ramp",
    @"43",  @"436-EHV-0-1001-0030-I_limited",
    @"44",  @"436-EHV-0-1001-0031-warning",
    @"45",  @"436-EHV-0-1001-0032-error",
    @"46",  @"436-EHV-0-1002-0001-U_set",
    @"47",  @"436-EHV-0-1002-0002-U_act",
    @"48",  @"436-EHV-0-1002-0003-I_max",
    @"49",  @"436-EHV-0-1002-0004-I_act",
    @"50",  @"436-EHV-0-1002-0005-U_ramp",
    @"51",  @"436-EHV-0-1002-0030-I_limited",
    @"52",  @"436-EHV-0-1002-0031-warning",
    @"53",  @"436-EHV-0-1002-0032-error",
    @"86",  @"436-EHV-0-1003-0001-U_set",
    @"87",  @"436-EHV-0-1003-0002-U_act",
    @"88",  @"436-EHV-0-1003-0003-I_max",
    @"89",  @"436-EHV-0-1003-0004-I_act",
    @"90",  @"436-EHV-0-1003-0005-U_ramp",
    @"91",  @"436-EHV-0-1003-0030-I_limited",
    @"92",  @"436-EHV-0-1003-0031-warning",
    @"93",  @"436-EHV-0-1003-0032-error",
    @"94",  @"416-EHV-0-1001-0001-U_set",
    @"95",  @"416-EHV-0-1001-0002-U_act",
    @"96",  @"416-EHV-0-1001-0003-I_max",
    @"97",  @"416-EHV-0-1001-0004-I_act",
    @"98",  @"416-EHV-0-1001-0005-U_ramp",
    @"99",  @"416-EHV-0-1001-0030-I_limited",
    @"100", @"416-EHV-0-1001-0031-warning",
    @"101", @"416-EHV-0-1001-0032-error",
    @"303", @"436-REU-0-0201-0001-U_act",
    @"304", @"436-REU-0-0201-0020-trigger_time",
    @"305", @"436-REU-0-0201-0030-meas_flag",
    @"306", @"436-REU-0-0301-0001-U_act",
    @"307", @"436-REU-0-0301-0020-trigger_time",
    @"308", @"436-REU-0-0301-0030-meas_flag",
    */
};



//
//  113-RS e-gun embedded PC
//

static NSString* setPointList_RS2[] = {
     @"-", @"Timestamp 1 [EgunRS_EPC Timestamps SOLL]",
    @"-", @"Timestamp 2 [EgunRS_EPC Timestamps SOLL]",
    @"111-LGU-0-2300-0100", @"[number] Optical fiber ID     [Optic System EPC SOLL]",
    @"111-AAI-0-2301-0100", @"[mm]  Translation Stage X position     [Optic System EPC SOLL]",
    @"111-AAI-0-2302-0100", @"[mm]  Translation Stage Y position     [Optic System EPC SOLL]",
    @"111-AAI-0-2303-0100", @"[mm]  Translation Stage Z position     [Optic System EPC SOLL]",
    @"111-AAI-0-2601-0100", @"[set] Noise Eater Regulation ON/OFF     [Optic System EPC SOLL]",
    @"111-AAI-0-2601-0101", @"[voltage] NoiseEater Regulation Setpoint     [Optic System EPC SOLL]",
    @"110-REI-0-1110-0100", @"[range] Rear Wall Current Range     [Optic System EPC SOLL]",
    @"-", @"Reserved     [Optic System EPC SOLL]",
    @"-", @"Reserved     [Optic System EPC SOLL]",
    @"-", @"Reserved     [Optic System EPC SOLL]",
    @"-", @"Reserved     [Optic System EPC SOLL]",
    @"-", @"Reserved     [Optic System EPC SOLL]",
    @"-", @"Reserved     [Optic System EPC SOLL]",
    @"-", @"Reserved     [Optic System EPC SOLL]",
    @"-", @"Reserved [Optic System EPC SOLL]",
    @"", @""
};

static NSString* measuredValueList_RS2[] = {
    @"-", @"Timestamp 1 [EgunRS_EPC Timestamps IST]",
    @"-", @"Timestamp 2 [EgunRS_EPC Timestamps IST]",
    @"111-LGU-0-2300-0000", @"[number] Optical fiber ID     [Optic System EPC IST]",
    @"111-AAI-0-2301-0000", @"[mm] Translation Stage X position     [Optic System EPC IST]",
    @"111-AAI-0-2301-0001", @"[status] Translation Stage X on position?     [Optic System EPC IST]",
    @"111-AAI-0-2301-0002", @"[status] Translation Stage X status     [Optic System EPC IST]",
    @"111-AAI-0-2302-0000", @"[mm] Translation Stage Y position     [Optic System EPC IST]",
    @"111-AAI-0-2302-0001", @"[status] Translation Stage Y on position?     [Optic System EPC IST]",
    @"111-AAI-0-2302-0002", @"[status] Translation Stage Y status     [Optic System EPC IST]",
    @"111-AAI-0-2303-0000", @"[mm] Translation Stage Z position     [Optic System EPC IST]",
    @"111-AAI-0-2303-0001", @"[status] Translation Stage Z on position?     [Optic System EPC IST]",
    @"111-AAI-0-2303-0002", @"[status] Translation Stage Z status     [Optic System EPC IST]",
    @"111-AAI-0-2601-0001", @"[voltage/milli] Noise Eater Readout     [Optic System EPC IST]",
    @"111-AAI-0-2601-0002", @"[voltage] Noise Eater clipped?     [Optic System EPC IST]",
    @"110-REI-0-1110-0000", @"[current] Rear Wall Current     [Optic System EPC IST]",
    @"110-REI-0-1110-0001", @"[status] Rear Wall Current Status     [Optic System EPC IST]",
    @"-", @"Reserved     [Optic System EPC IST]",
    @"-", @"Reserved     [Optic System EPC IST]",
    @"-", @"Reserved     [Optic System EPC IST]",
    @"-", @"Reserved     [Optic System EPC IST]",
    @"-", @"Reserved     [Optic System EPC IST]",
    @"-", @"Reserved     [Optic System EPC IST]",
    @"-", @"Reserved     [Optic System EPC IST]",
    @"-", @"Reserved     [Optic System EPC IST]",
    @"-", @"Reserved     [Optic System EPC IST]",
    @"-", @"Reserved     [Optic System EPC IST]",
    @"-", @"Reserved [Optic System EPC IST]",
    @"", @""
};

#define kNumToShip_RS2  0 //
static NSString* itemsToShip_RS2[kNumToShip_RS2*2] = {
/*
    @"38",  @"436-EHV-0-1001-0001-U_set",
    @"39",  @"436-EHV-0-1001-0002-U_act",
    @"40",  @"436-EHV-0-1001-0003-I_max",
    @"41",  @"436-EHV-0-1001-0004-I_act",
    @"42",  @"436-EHV-0-1001-0005-U_ramp",
    @"43",  @"436-EHV-0-1001-0030-I_limited",
    @"44",  @"436-EHV-0-1001-0031-warning",
    @"45",  @"436-EHV-0-1001-0032-error",
    @"46",  @"436-EHV-0-1002-0001-U_set",
    @"47",  @"436-EHV-0-1002-0002-U_act",
    @"48",  @"436-EHV-0-1002-0003-I_max",
    @"49",  @"436-EHV-0-1002-0004-I_act",
    @"50",  @"436-EHV-0-1002-0005-U_ramp",
    @"51",  @"436-EHV-0-1002-0030-I_limited",
    @"52",  @"436-EHV-0-1002-0031-warning",
    @"53",  @"436-EHV-0-1002-0032-error",
    @"86",  @"436-EHV-0-1003-0001-U_set",
    @"87",  @"436-EHV-0-1003-0002-U_act",
    @"88",  @"436-EHV-0-1003-0003-I_max",
    @"89",  @"436-EHV-0-1003-0004-I_act",
    @"90",  @"436-EHV-0-1003-0005-U_ramp",
    @"91",  @"436-EHV-0-1003-0030-I_limited",
    @"92",  @"436-EHV-0-1003-0031-warning",
    @"93",  @"436-EHV-0-1003-0032-error",
    @"94",  @"416-EHV-0-1001-0001-U_set",
    @"95",  @"416-EHV-0-1001-0002-U_act",
    @"96",  @"416-EHV-0-1001-0003-I_max",
    @"97",  @"416-EHV-0-1001-0004-I_act",
    @"98",  @"416-EHV-0-1001-0005-U_ramp",
    @"99",  @"416-EHV-0-1001-0030-I_limited",
    @"100", @"416-EHV-0-1001-0031-warning",
    @"101", @"416-EHV-0-1001-0032-error",
    @"303", @"436-REU-0-0201-0001-U_act",
    @"304", @"436-REU-0-0201-0020-trigger_time",
    @"305", @"436-REU-0-0201-0030-meas_flag",
    @"306", @"436-REU-0-0301-0001-U_act",
    @"307", @"436-REU-0-0301-0020-trigger_time",
    @"308", @"436-REU-0-0301-0030-meas_flag",
    */
};


//
// 436 High voltage
//

//new lists from 10/17/2017   -mah-
static NSString* setPointList_HV[] = {
    @"-",    @"Timestamp 1",
    @"-",    @"Timestamp 2",
    @"SOLL_PXI_MODUL#WestModul0",    @"Rampe",
    @"SOLL_PXI_MODUL#WestModul1",    @"Rampe",
    @"SOLL_PXI_MODUL#WestModul2",    @"Rampe",
    @"SOLL_PXI_MODUL#EastModul0",    @"Rampe",
    @"SOLL_PXI_MODUL#EastModul1",    @"Rampe",
    @"SOLL_PXI_MODUL#EastModul2",    @"Rampe",
    @"SOLL_PXI_CHANNEL#WestCh0",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh0",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh0",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh1",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh1",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh1",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh2",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh2",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh2",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh3",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh3",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh3",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh4",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh4",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh4",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh5",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh5",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh5",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh6",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh6",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh6",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh7",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh7",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh7",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh8",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh8",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh8",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh9",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh9",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh9",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh10",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh10",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh10",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh11",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh11",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh11",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh12",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh12",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh12",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh13",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh13",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh13",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh14",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh14",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh14",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh15",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh15",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh15",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh16",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh16",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh16",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh17",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh17",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh17",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh18",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh18",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh18",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh19",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh19",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh19",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh20",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh20",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh20",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh21",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh21",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh21",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh22",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh22",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh22",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh23",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh23",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh23",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh0",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh0",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh0",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh1",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh1",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh1",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh2",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh2",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh2",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh3",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh3",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh3",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh4",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh4",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh4",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh5",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh5",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh5",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh6",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh6",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh6",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh7",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh7",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh7",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh8",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh8",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh8",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh9",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh9",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh9",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh10",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh10",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh10",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh11",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh11",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh11",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh12",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh12",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh12",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh13",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh13",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh13",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh14",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh14",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh14",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh15",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh15",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh15",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh16",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh16",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh16",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh17",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh17",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh17",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh18",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh18",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh18",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh19",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh19",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh19",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh20",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh20",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh20",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh21",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh21",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh21",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh22",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh22",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh22",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh23",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh23",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh23",    @"U_EXAKT",
    @"SOLL_EHV#mainSpecVesel",    @"U_Soll",
    @"SOLL_EHV#mainSpecVesel",    @"I_MAX",
    @"SOLL_EHV#mainSpecVesel",    @"Rampe",
    @"SOLL_EHV#mainSpecElektrode",    @"U_Soll",
    @"SOLL_EHV#mainSpecElektrode",    @"I_MAX",
    @"SOLL_EHV#mainSpecElektrode",    @"Rampe",
    @"SOLL_EHV#mainSpecCorrSouth",    @"U_Soll",
    @"SOLL_EHV#mainSpecCorrSouth",    @"I_MAX",
    @"SOLL_EHV#mainSpecCorrSouth",    @"Rampe",
    @"SOLL_EHV#mainSpecCorrWest",    @"U_Soll",
    @"SOLL_EHV#mainSpecCorrWest",    @"I_MAX",
    @"SOLL_EHV#mainSpecCorrWest",    @"Rampe",
    @"SOLL_EHV#mainSpecDipolWest",    @"U_Soll",
    @"SOLL_EHV#mainSpecDipolWest",    @"I_MAX",
    @"SOLL_EHV#mainSpecDipolWest",    @"Rampe",
    @"SOLL_EHV#mainSpecDipolEast",    @"U_Soll",
    @"SOLL_EHV#mainSpecDipolEast",    @"I_MAX",
    @"SOLL_EHV#mainSpecDipolEast",    @"Rampe",
    @"SOLL_EHV#IECommon",    @"U_Soll",
    @"SOLL_EHV#IECommon",    @"I_MAX",
    @"SOLL_EHV#IECommon",    @"Rampe",
    @"SOLL_EHV#preSpecVesel",    @"U_Soll",
    @"SOLL_EHV#preSpecVesel",    @"I_MAX",
    @"SOLL_EHV#preSpecVesel",    @"Rampe",
    @"SOLL_EHV#preSpecIE1",    @"U_Soll",
    @"SOLL_EHV#preSpecIE1",    @"I_MAX",
    @"SOLL_EHV#preSpecIE1",    @"Rampe",
    @"SOLL_EHV#preSpecIE2",    @"U_Soll",
    @"SOLL_EHV#preSpecIE2",    @"I_MAX",
    @"SOLL_EHV#preSpecIE2",    @"Rampe",
    @"SOLL_EHV#preSpecIE3",    @"U_Soll",
    @"SOLL_EHV#preSpecIE3",    @"I_MAX",
    @"SOLL_EHV#preSpecIE3",    @"Rampe",
    @"SOLL_EHV#preSpecIE4",    @"U_Soll",
    @"SOLL_EHV#preSpecIE4",    @"I_MAX",
    @"SOLL_EHV#preSpecIE4",    @"Rampe",
    @"SOLL_STATUS#Ost_Relais",    @"Bed",
    @"SOLL_STATUS#Ost_Relais",    @"Modus",
    @"SOLL_STATUS#Ost_Relais",    @"Time_On",
    @"SOLL_STATUS#Ost_Relais",    @"Time_Off",
    @"SOLL_STATUS#West_Relais",    @"Bed",
    @"SOLL_STATUS#West_Relais",    @"Modus",
    @"SOLL_STATUS#West_Relais",    @"Time_On",
    @"SOLL_STATUS#West_Relais",    @"Time_Off",
    @"SOLL_EHV#postReg",    @"U_Soll",
    @"SOLL_EHV#postRegInhibit",    @"Status",
    @"", @""
};

static NSString* measuredValueList_HV[] = {
    @"-",    @"Timestamp 1",
    @"-",    @"Timestamp 2",
    @"IST_PXI_MODUL#WestModul0",    @"Temperatur Board",
    @"IST_PXI_MODUL#WestModul0",    @"24 Spannung",
    @"IST_PXI_MODUL#WestModul0",    @"5V Spannung",
    @"IST_PXI_MODUL#WestModul0",    @"Rampe",
    @"IST_PXI_MODUL#WestModul0",    @"Warnung",
    @"IST_PXI_MODUL#WestModul0",    @"Fehler",
    @"IST_PXI_MODUL#WestModul1",    @"Temperatur Board",
    @"IST_PXI_MODUL#WestModul1",    @"24 Spannung",
    @"IST_PXI_MODUL#WestModul1",    @"5V Spannung",
    @"IST_PXI_MODUL#WestModul1",    @"Rampe",
    @"IST_PXI_MODUL#WestModul1",    @"Warnung",
    @"IST_PXI_MODUL#WestModul1",    @"Fehler",
    @"IST_PXI_MODUL#WestModul2",    @"Temperatur Board",
    @"IST_PXI_MODUL#WestModul2",    @"24 Spannung",
    @"IST_PXI_MODUL#WestModul2",    @"5V Spannung",
    @"IST_PXI_MODUL#WestModul2",    @"Rampe",
    @"IST_PXI_MODUL#WestModul2",    @"Warnung",
    @"IST_PXI_MODUL#WestModul2",    @"Fehler",
    @"IST_PXI_MODUL#EastModul0",    @"Temperatur Board",
    @"IST_PXI_MODUL#EastModul0",    @"24 Spannung",
    @"IST_PXI_MODUL#EastModul0",    @"5V Spannung",
    @"IST_PXI_MODUL#EastModul0",    @"Rampe",
    @"IST_PXI_MODUL#EastModul0",    @"Warnung",
    @"IST_PXI_MODUL#EastModul0",    @"Fehler",
    @"IST_PXI_MODUL#EastModul1",    @"Temperatur Board",
    @"IST_PXI_MODUL#EastModul1",    @"24 Spannung",
    @"IST_PXI_MODUL#EastModul1",    @"5V Spannung",
    @"IST_PXI_MODUL#EastModul1",    @"Rampe",
    @"IST_PXI_MODUL#EastModul1",    @"Warnung",
    @"IST_PXI_MODUL#EastModul1",    @"Fehler",
    @"IST_PXI_MODUL#EastModul2",    @"Temperatur Board",
    @"IST_PXI_MODUL#EastModul2",    @"24 Spannung",
    @"IST_PXI_MODUL#EastModul2",    @"5V Spannung",
    @"IST_PXI_MODUL#EastModul2",    @"Rampe",
    @"IST_PXI_MODUL#EastModul2",    @"Warnung",
    @"IST_PXI_MODUL#EastModul2",    @"Fehler",
    @"IST_EHV#mainSpecVessel",    @"U_SOLL",
    @"IST_EHV#mainSpecVessel",    @"U_IST",
    @"IST_EHV#mainSpecVessel",    @"I_MAX",
    @"IST_EHV#mainSpecVessel",    @"I_IST",
    @"IST_EHV#mainSpecVessel",    @"Rampe",
    @"IST_EHV#mainSpecVessel",    @"I_Begrenzt",
    @"IST_EHV#mainSpecVessel",    @"Warnung",
    @"IST_EHV#mainSpecVessel",    @"Fehler",
    @"IST_EHV#mainSpecElektrode",    @"U_SOLL",
    @"IST_EHV#mainSpecElektrode",    @"U_IST",
    @"IST_EHV#mainSpecElektrode",    @"I_MAX",
    @"IST_EHV#mainSpecElektrode",    @"I_IST",
    @"IST_EHV#mainSpecElektrode",    @"Rampe",
    @"IST_EHV#mainSpecElektrode",    @"I_Begrenzt",
    @"IST_EHV#mainSpecElektrode",    @"Warnung",
    @"IST_EHV#mainSpecElektrode",    @"Fehler",
    @"IST_EHV#mainSpecCorrSouth",    @"U_SOLL",
    @"IST_EHV#mainSpecCorrSouth",    @"U_IST",
    @"IST_EHV#mainSpecCorrSouth",    @"I_MAX",
    @"IST_EHV#mainSpecCorrSouth",    @"I_IST",
    @"IST_EHV#mainSpecCorrSouth",    @"Rampe",
    @"IST_EHV#mainSpecCorrSouth",    @"I_Begrenzt",
    @"IST_EHV#mainSpecCorrSouth",    @"Warnung",
    @"IST_EHV#mainSpecCorrSouth",    @"Fehler",
    @"IST_EHV#mainSpecCorrNorth",    @"U_SOLL",
    @"IST_EHV#mainSpecCorrNorth",    @"U_IST",
    @"IST_EHV#mainSpecCorrNorth",    @"I_MAX",
    @"IST_EHV#mainSpecCorrNorth",    @"I_IST",
    @"IST_EHV#mainSpecCorrNorth",    @"Rampe",
    @"IST_EHV#mainSpecCorrNorth",    @"I_Begrenzt",
    @"IST_EHV#mainSpecCorrNorth",    @"Warnung",
    @"IST_EHV#mainSpecCorrNorth",    @"Fehler",
    @"IST_EHV#mainSpecDipolWest",    @"U_SOLL",
    @"IST_EHV#mainSpecDipolWest",    @"U_IST",
    @"IST_EHV#mainSpecDipolWest",    @"I_MAX",
    @"IST_EHV#mainSpecDipolWest",    @"I_IST",
    @"IST_EHV#mainSpecDipolWest",    @"Rampe",
    @"IST_EHV#mainSpecDipolWest",    @"I_Begrenzt",
    @"IST_EHV#mainSpecDipolWest",    @"Warnung",
    @"IST_EHV#mainSpecDipolWest",    @"Fehler",
    @"IST_EHV#mainSpecDipolEast",    @"U_SOLL",
    @"IST_EHV#mainSpecDipolEast",    @"U_IST",
    @"IST_EHV#mainSpecDipolEast",    @"I_MAX",
    @"IST_EHV#mainSpecDipolEast",    @"I_IST",
    @"IST_EHV#mainSpecDipolEast",    @"Rampe",
    @"IST_EHV#mainSpecDipolEast",    @"I_Begrenzt",
    @"IST_EHV#mainSpecDipolEast",    @"Warnung",
    @"IST_EHV#mainSpecDipolEast",    @"Fehler",
    @"IST_EHV#IECommon",    @"U_SOLL",
    @"IST_EHV#IECommon",    @"U_IST",
    @"IST_EHV#IECommon",    @"I_MAX",
    @"IST_EHV#IECommon",    @"I_IST",
    @"IST_EHV#IECommon",    @"Rampe",
    @"IST_EHV#IECommon",    @"I_Begrenzt",
    @"IST_EHV#IECommon",    @"Warnung",
    @"IST_EHV#IECommon",    @"Fehler",
    @"IST_EHV#preSpecVesel",    @"U_SOLL",
    @"IST_EHV#preSpecVesel",    @"U_IST",
    @"IST_EHV#preSpecVesel",    @"I_MAX",
    @"IST_EHV#preSpecVesel",    @"I_IST",
    @"IST_EHV#preSpecVesel",    @"Rampe",
    @"IST_EHV#preSpecVesel",    @"I_Begrenzt",
    @"IST_EHV#preSpecVesel",    @"Warnung",
    @"IST_EHV#preSpecVesel",    @"Fehler",
    @"IST_EHV#preSpecIE1",    @"U_SOLL",
    @"IST_EHV#preSpecIE1",    @"U_IST",
    @"IST_EHV#preSpecIE1",    @"I_MAX",
    @"IST_EHV#preSpecIE1",    @"I_IST",
    @"IST_EHV#preSpecIE1",    @"Rampe",
    @"IST_EHV#preSpecIE1",    @"I_Begrenzt",
    @"IST_EHV#preSpecIE1",    @"Warnung",
    @"IST_EHV#preSpecIE1",    @"Fehler",
    @"IST_EHV#preSpecIE2",    @"U_SOLL",
    @"IST_EHV#preSpecIE2",    @"U_IST",
    @"IST_EHV#preSpecIE2",    @"I_MAX",
    @"IST_EHV#preSpecIE2",    @"I_IST",
    @"IST_EHV#preSpecIE2",    @"Rampe",
    @"IST_EHV#preSpecIE2",    @"I_Begrenzt",
    @"IST_EHV#preSpecIE2",    @"Warnung",
    @"IST_EHV#preSpecIE2",    @"Fehler",
    @"IST_EHV#preSpecIE3",    @"U_SOLL",
    @"IST_EHV#preSpecIE3",    @"U_IST",
    @"IST_EHV#preSpecIE3",    @"I_MAX",
    @"IST_EHV#preSpecIE3",    @"I_IST",
    @"IST_EHV#preSpecIE3",    @"Rampe",
    @"IST_EHV#preSpecIE3",    @"I_Begrenzt",
    @"IST_EHV#preSpecIE3",    @"Warnung",
    @"IST_EHV#preSpecIE3",    @"Fehler",
    @"IST_EHV#preSpecIE4",    @"U_SOLL",
    @"IST_EHV#preSpecIE4",    @"U_IST",
    @"IST_EHV#preSpecIE4",    @"I_MAX",
    @"IST_EHV#preSpecIE4",    @"I_IST",
    @"IST_EHV#preSpecIE4",    @"Rampe",
    @"IST_EHV#preSpecIE4",    @"I_Begrenzt",
    @"IST_EHV#preSpecIE4",    @"Warnung",
    @"IST_EHV#preSpecIE4",    @"Fehler",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Temperatur_1",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Temperatur_2",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Luftfeuchte",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Spannung",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Warnung",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Fehler",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Temperatur_1",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Temperatur_2",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Luftfeuchte",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Spannung",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Warnung",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Fehler",
    @"IST_cRIO_STATUS#ExpPC_SollSet",    @"Zustand",
    @"IST_cRIO_STATUS#ZEUS_SollSet",    @"Zustand",
    @"IST_cRIO_STATUS#ORCA_SollSet",    @"Zustand",
    @"IST_cRIO_STATUS#416Status_OK",    @"Zustand",
    @"IST_cRIO_STATUS#416HV_Freigabe",    @"Zustand",
    @"IST_cRIO_STATUS#416HV_aktiv",    @"Zustand",
    @"IST_cRIO_STATUS#436Status_OK",    @"Zustand",
    @"IST_cRIO_STATUS#436HV_Freigabe",    @"Zustand",
    @"IST_cRIO_STATUS#436HV_aktiv",    @"Zustand",
    @"IST_cRIO_STATUS#436VAO_AUF",    @"Zustand",
    @"IST_cRIO_STATUS#436HV_gekoppelt",    @"Zustand",
    @"IST_HV_RELAIS#Ost_Relais",    @"Zustand",
    @"IST_HV_RELAIS#West_Relais",    @"Zustand",
    @"IST_PXI_VOLTAGE#WestCh0",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh0",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh0",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh1",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh1",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh1",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh2",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh2",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh2",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh3",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh3",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh3",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh4",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh4",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh4",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh5",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh5",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh5",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh6",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh6",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh6",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh7",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh7",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh7",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh8",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh8",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh8",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh9",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh9",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh9",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh10",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh10",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh10",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh11",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh11",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh11",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh12",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh12",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh12",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh13",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh13",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh13",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh14",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh14",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh14",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh15",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh15",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh15",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh16",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh16",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh16",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh17",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh17",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh17",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh18",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh18",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh18",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh19",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh19",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh19",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh20",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh20",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh20",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh21",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh21",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh21",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh22",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh22",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh22",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh23",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh23",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh23",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh0",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh0",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh0",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh1",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh1",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh1",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh2",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh2",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh2",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh3",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh3",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh3",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh4",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh4",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh4",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh5",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh5",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh5",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh6",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh6",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh6",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh7",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh7",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh7",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh8",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh8",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh8",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh9",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh9",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh9",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh10",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh10",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh10",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh11",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh11",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh11",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh12",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh12",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh12",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh13",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh13",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh13",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh14",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh14",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh14",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh15",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh15",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh15",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh16",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh16",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh16",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh17",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh17",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh17",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh18",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh18",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh18",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh19",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh19",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh19",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh20",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh20",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh20",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh21",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh21",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh21",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh22",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh22",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh22",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh23",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh23",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh23",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#35KV_U",    @"U_IST",
    @"IST_PXI_VOLTAGE#35KV_U",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#35KV_U",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#65KV_U",    @"U_IST",
    @"IST_PXI_VOLTAGE#65KV_U",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#65KV_U",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#KAL_U1",    @"U_IST",
    @"IST_PXI_VOLTAGE#KAL_U1",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#KAL_U1",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#KAL_U2",    @"U_IST",
    @"IST_PXI_VOLTAGE#KAL_U2",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#KAL_U2",    @"Messung lauft",
    @"IST_PXI_CHANNEL#WestCh0",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh0",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh0",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh0",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh0",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh0",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh0",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh1",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh1",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh1",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh1",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh1",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh1",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh1",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh2",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh2",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh2",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh2",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh2",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh2",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh2",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh3",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh3",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh3",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh3",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh3",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh3",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh3",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh4",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh4",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh4",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh4",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh4",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh4",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh4",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh5",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh5",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh5",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh5",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh5",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh5",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh5",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh6",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh6",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh6",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh6",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh6",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh6",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh6",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh7",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh7",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh7",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh7",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh7",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh7",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh7",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh8",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh8",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh8",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh8",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh8",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh8",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh8",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh9",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh9",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh9",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh9",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh9",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh9",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh9",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh10",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh10",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh10",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh10",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh10",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh10",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh10",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh11",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh11",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh11",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh11",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh11",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh11",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh11",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh12",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh12",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh12",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh12",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh12",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh12",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh12",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh13",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh13",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh13",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh13",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh13",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh13",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh13",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh14",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh14",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh14",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh14",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh14",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh14",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh14",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh15",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh15",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh15",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh15",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh15",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh15",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh15",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh16",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh16",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh16",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh16",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh16",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh16",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh16",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh17",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh17",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh17",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh17",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh17",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh17",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh17",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh18",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh18",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh18",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh18",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh18",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh18",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh18",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh19",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh19",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh19",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh19",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh19",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh19",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh19",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh20",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh20",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh20",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh20",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh20",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh20",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh20",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh21",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh21",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh21",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh21",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh21",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh21",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh21",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh22",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh22",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh22",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh22",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh22",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh22",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh22",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh23",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh23",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh23",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh23",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh23",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh23",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh23",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh0",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh0",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh0",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh0",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh0",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh0",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh0",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh1",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh1",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh1",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh1",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh1",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh1",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh1",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh2",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh2",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh2",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh2",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh2",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh2",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh2",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh3",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh3",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh3",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh3",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh3",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh3",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh3",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh4",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh4",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh4",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh4",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh4",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh4",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh4",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh5",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh5",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh5",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh5",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh5",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh5",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh5",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh6",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh6",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh6",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh6",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh6",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh6",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh6",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh7",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh7",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh7",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh7",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh7",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh7",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh7",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh8",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh8",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh8",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh8",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh8",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh8",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh8",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh9",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh9",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh9",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh9",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh9",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh9",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh9",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh10",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh10",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh10",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh10",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh10",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh10",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh10",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh11",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh11",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh11",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh11",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh11",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh11",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh11",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh12",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh12",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh12",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh12",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh12",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh12",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh12",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh13",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh13",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh13",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh13",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh13",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh13",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh13",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh14",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh14",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh14",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh14",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh14",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh14",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh14",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh15",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh15",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh15",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh15",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh15",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh15",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh15",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh16",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh16",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh16",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh16",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh16",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh16",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh16",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh17",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh17",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh17",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh17",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh17",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh17",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh17",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh18",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh18",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh18",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh18",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh18",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh18",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh18",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh19",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh19",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh19",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh19",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh19",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh19",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh19",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh20",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh20",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh20",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh20",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh20",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh20",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh20",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh21",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh21",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh21",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh21",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh21",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh21",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh21",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh22",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh22",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh22",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh22",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh22",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh22",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh22",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh23",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh23",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh23",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh23",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh23",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh23",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh23",    @"Fehler",
    @"IST_EHV#postReg",    @"U_IST",
    @"IST_EHV#postRegInhibit",    @"Inh_IST",
    @"IST_EHV#postRegStatus",    @"Status",
    @"", @""
};

#define kNumToShip_HV  38
static NSString* itemsToShip_HV[kNumToShip_HV*2] = {
    @"38",  @"436-EHV-0-1001-0001-U_set",
    @"39",  @"436-EHV-0-1001-0002-U_act",
    @"40",  @"436-EHV-0-1001-0003-I_max",
    @"41",  @"436-EHV-0-1001-0004-I_act",
    @"42",  @"436-EHV-0-1001-0005-U_ramp",
    @"43",  @"436-EHV-0-1001-0030-I_limited",
    @"44",  @"436-EHV-0-1001-0031-warning",
    @"45",  @"436-EHV-0-1001-0032-error",
    @"46",  @"436-EHV-0-1002-0001-U_set",
    @"47",  @"436-EHV-0-1002-0002-U_act",
    @"48",  @"436-EHV-0-1002-0003-I_max",
    @"49",  @"436-EHV-0-1002-0004-I_act",
    @"50",  @"436-EHV-0-1002-0005-U_ramp",
    @"51",  @"436-EHV-0-1002-0030-I_limited",
    @"52",  @"436-EHV-0-1002-0031-warning",
    @"53",  @"436-EHV-0-1002-0032-error",
    @"86",  @"436-EHV-0-1003-0001-U_set",
    @"87",  @"436-EHV-0-1003-0002-U_act",
    @"88",  @"436-EHV-0-1003-0003-I_max",
    @"89",  @"436-EHV-0-1003-0004-I_act",
    @"90",  @"436-EHV-0-1003-0005-U_ramp",
    @"91",  @"436-EHV-0-1003-0030-I_limited",
    @"92",  @"436-EHV-0-1003-0031-warning",
    @"93",  @"436-EHV-0-1003-0032-error",
    @"94",  @"416-EHV-0-1001-0001-U_set",
    @"95",  @"416-EHV-0-1001-0002-U_act",
    @"96",  @"416-EHV-0-1001-0003-I_max",
    @"97",  @"416-EHV-0-1001-0004-I_act",
    @"98",  @"416-EHV-0-1001-0005-U_ramp",
    @"99",  @"416-EHV-0-1001-0030-I_limited",
    @"100", @"416-EHV-0-1001-0031-warning",
    @"101", @"416-EHV-0-1001-0032-error",
    @"303", @"436-REU-0-0201-0001-U_act",
    @"304", @"436-REU-0-0201-0020-trigger_time",
    @"305", @"436-REU-0-0201-0030-meas_flag",
    @"306", @"436-REU-0-0301-0001-U_act",
    @"307", @"436-REU-0-0301-0020-trigger_time",
    @"308", @"436-REU-0-0301-0030-meas_flag",
};


//
// FPD PAK board
//


//
// CPS
//

/*
Soll-Werte:
310-EEL-3-1000-0041 (Dipol 1 upper half shell)
310-EEL-3-1010-0041 (Dipol 1 lower half shell)
310-EEL-3-2000-0041 (Dipol 2 upper half shell)
310-EEL-3-2010-0041 (Dipol 2 lower half shell)
310-EEL-3-3000-0041 (Dipol 3 upper half shell)
310-EEL-3-3010-0041 (Dipol 3 lower half shell)

Read-Werte:
310-EEL-3-1000-0001
310-EEL-3-1010-0001
310-EEL-3-2000-0001
310-EEL-3-2010-0001
310-EEL-3-3000-0001
310-EEL-3-3010-0001
*/

static NSString* setPointList_DPS[] = {
    @"-", @"Timestamp 1",
    @"-", @"Timestamp 2",
    @"310-EEL-3-1000-0041", @"Dipol 1 upper half shell",
    @"310-EEL-3-1010-0041", @"Dipol 1 lower half shell",
    @"310-EEL-3-2000-0041", @"Dipol 2 upper half shell",
    @"310-EEL-3-2010-0041", @"Dipol 2 lower half shell",
    @"310-EEL-3-3000-0041", @"Dipol 3 upper half shell",
    @"310-EEL-3-3010-0041", @"Dipol 3 lower half shell",
    @"", @""
};

static NSString* measuredValueList_DPS[] = {
    @"-", @"Timestamp 1",
    @"-", @"Timestamp 2",
    @"310-EEL-3-1000-0001", @"Dipol 1 upper half shell",
    @"310-EEL-3-1010-0001", @"Dipol 1 lower half shell",
    @"310-EEL-3-2000-0001", @"Dipol 2 upper half shell",
    @"310-EEL-3-2010-0001", @"Dipol 2 lower half shell",
    @"310-EEL-3-3000-0001", @"Dipol 3 upper half shell",
    @"310-EEL-3-3010-0001", @"Dipol 3 lower half shell",
    @"", @""
};

#define kNumToShip_DPS  0 //
static NSString* itemsToShip_DPS[kNumToShip_DPS*2] = {
};


//
// DAQlab (similar to RS configuration)
//

static NSString* setPointList_DAQlab[] = {
    @"-", @"Timestamp 1",
    @"-", @"Timestamp 2",
    @"113-ELV-1-0101-0100", @"Booster Coil Rear Voltage ",
    @"113-ELV-1-0101-0101", @"Booster Coil Rear Current ",
    @"113-ELV-1-0201-0100", @"Booster Coil Front Voltage ",
    @"113-ELV-1-0201-0101", @"Booster Coil Front Current ",
    @"113-ELV-1-0301-0100", @"Solenoid Rear Voltage ",
    @"113-ELV-1-0301-0101", @"Solenoid Rear Current ",
    @"113-ELV-1-0401-0100", @"Solenoid Middle Voltage ",
    @"113-ELV-1-0401-0101", @"Solenoid Middle Current ",
    @"113-ELV-1-0501-0100", @"Solenoid Front Voltage ",
    @"113-ELV-1-0501-0101", @"Solenoid Front  Current ",
    @"113-ELV-1-0601-0100", @"Steearing  Coil X Voltage ",
    @"113-ELV-1-0601-0101", @"Steearing Coil X Current ",
    @"113-ELV-1-0602-0100", @"Steearing  Coil Y Voltage ",
    @"113-ELV-1-0602-0101", @"Steearing Coil Y Current ",
    @"113-ELV-1-0603-0100", @"Compensation  Coil X Voltage ",
    @"113-ELV-1-0603-0101", @"Compensation Coil X Current ",
    @"113-ELV-1-0604-0100", @"Compensation  Coil Y Voltage ",
    @"113-ELV-1-0604-0101", @"Compensation Coil Y Current ",
    @"111-EHV-0-1101-0101", @"mission electrode Voltage ",
    @"111-EHV-0-1101-0102", @"mission electrode Current ",
    @"111-EHV-0-1102-0101", @"Acceleration electrode Voltage ",
    @"111-EHV-0-1102-0102", @"Acceleration electrode Current ",
    @"111-EHV-0-1100-0100", @"lectrode difference Voltage ",
    @"111-REU-0-1201-0100", @"mission electrode DVM Voltage Range ",
    @"111-EHV-0-1301-0100", @"Dipole electrode West Voltage ",
    @"111-EHV-0-1302-0100", @"Dipole electrode East Voltage ",
    @"212-EHV-0-1300-0100", @"Rear wall  PS Voltage ",
    @"-", @"Reserved",
    @"111-RTY-0-2102-0100", @"LDLS Temperature Controller Temperature ",
    @"111-LFI-0-2103-0100", @"Monochromator Wavelegth ",
    @"111-LFI-0-2103-0101", @"Monochromator Spectral Resolution ",
    @"111-REI-0-2401-0100", @"Beam Monitor Amplifier Amplification coeficient ",
    @"111-REI-0-2401-0101", @"Beam Monitor Range ",
    @"111-LUV-0-2501-0103", @" Laser Pulse Frequency ",
    @"111-LUV-0-2501-0104", @" Laser diode operating current ",
    @"111-CPS-0-2502-0101", @"ulser frequency ",
    @"111-CPS-0-2502-0102", @"ulser amplitude ",
    @"111-CPS-0-2502-0103", @"ulser pulse length ",
    @"111-LUV-0-2101-0100", @"DLS ON/OFF ",
    @"111-REI-0-2401-0100", @"Beam Monitor Amplifier Coupling ",
    @"111-REI-0-2401-0100", @"Beam Monitor Amplifier Hi/Low Speed ",
    @"111-LUV-0-2501-0100", @" Laser Shutter open/close ",
    @"111-LUV-0-2501-0101", @" Laser diode standby ON-OFF ",
    @"111-LUV-0-2501-0102", @" Laser Trigger Mode Int/Ext ",
    @"113-ELV-1-0500-0100", @"TDK Set ",
    @"113-ELV-1-0600-0100", @"R&S Set ",
    @"111-EHV-1-1600-0100", @"ISEG 500V Set ",
    @"111-EHV-1-1600-0101", @"ISEG 6kV Set ",
    @"111-EHV-1-1600-0102", @"Stahl HV Set ",
    @"111-AAI-0-3101-0101", @"Moog Start ",
    @"111-RTY-0-2102-0101", @"LDLS Temperature Controller ON-OFF ",
    @"", @""
};

static NSString* measuredValueList_DAQlab[] = {
    @"-", @"Timestamp 1",
    @"-", @"Timestamp 2",
    @"113-ELV-1-0101-0000", @"Booster Coil Rear Voltage ",
    @"113-ELV-1-0101-0001", @"Booster Coil Rear Current ",
    @"113-ELV-1-0101-0002", @"Booster Coil Rear Status ",
    @"113-ELV-1-0201-0000", @"Booster Coil Front Voltage ",
    @"113-ELV-1-0201-0001", @"Booster Coil Front Current ",
    @"113-ELV-1-0201-0002", @"Booster Coil Front Status ",
    @"113-ELV-1-0301-0000", @"Solenoid Rear Voltage ",
    @"113-ELV-1-0301-0001", @"Solenoid Rear Current ",
    @"113-ELV-1-0301-0002", @"Solenoid Rear Status ",
    @"113-ELV-1-0401-0000", @"Solenoid Middle Voltage ",
    @"113-ELV-1-0401-0001", @"Solenoid Middle Current ",
    @"113-ELV-1-0401-0002", @"Solenoid Middle Status ",
    @"113-ELV-1-0501-0000", @"Solenoid Front Voltage ",
    @"113-ELV-1-0501-0001", @"Solenoid Front Current ",
    @"113-ELV-1-0501-0002", @"Solenoid Front Status ",
    @"113-ELV-1-0601-0000", @"Steearing  Coil X Voltage ",
    @"113-ELV-1-0601-0001", @"Steearing Coil X Current ",
    @"113-ELV-1-0601-0002", @"Steearing Coil X Status ",
    @"113-ELV-1-0602-0000", @"Steearing  Coil Y Voltage ",
    @"113-ELV-1-0602-0001", @"Steearing Coil Y Current ",
    @"113-ELV-1-0602-0002", @"Steearing Coil Y Status ",
    @"113-ELV-1-0603-0000", @"Compensation  Coil X Voltage ",
    @"113-ELV-1-0603-0001", @"Compensation Coil X Current ",
    @"113-ELV-1-0603-0002", @"Compensation Coil X Status ",
    @"113-ELV-1-0604-0000", @"Compensation  Coil Y Voltage ",
    @"113-ELV-1-0604-0001", @"Compensation Coil Y Current ",
    @"113-ELV-1-0604-0002", @"Compensation Coil Y Status ",
    @"113-ELV-1-0600-0000", @"HMP4040 Power Output ",
    @"111-EHV-0-1101-0000", @"mission electrode Polarity ",
    @"111-EHV-0-1101-0001", @"mission electrode Voltage ",
    @"111-EHV-0-1101-0002", @"mission electrode Current ",
    @"111-EHV-0-1101-0003", @"mission electrode Status ",
    @"111-EHV-0-1102-0000", @"Acceleration electrode Polarity ",
    @"111-EHV-0-1102-0001", @"Acceleration electrode Voltage ",
    @"111-EHV-0-1102-0002", @"Acceleration electrode Current ",
    @"111-EHV-0-1102-0003", @"Acceleration electrode Status ",
    @"111-EHV-0-1100-0000", @"lectrode difference Voltage ",
    @"111-EHV-0-1100-0001", @"ISEG MMC Status ",
    @"111-REU-0-1201-0000", @"mission electrode DVM Voltage ",
    @"111-REU-0-1201-0001", @"mission electrode DVM Status ",
    @"111-EHV-0-1301-0000", @"Dipole electrode West Voltage ",
    @"111-EHV-0-1301-0001", @"Dipole electrode West Status ",
    @"111-EHV-0-1302-0000", @"Dipole electrode East Voltage ",
    @"111-EHV-0-1302-0001", @"Dipole electrode East Status ",
    @"212-EHV-0-1300-0000", @"Rear wall Voltage ",
    @"212-EHV-0-1300-0001", @"Rear wall Current ",
    @"212-EHV-0-1300-0002", @"Rear wall Status ",
    @"111-LUV-0-2101-0000", @"DLS External Interlock ",
    @"111-LUV-0-2101-0001", @"DLS LAMP ON ",
    @"111-LUV-0-2101-0002", @"DLS Laser ON ",
    @"111-LUV-0-2101-0003", @"DLS LAMP module fault ",
    @"111-LUV-0-2101-0004", @"DLS Controller fault ",
    @"111-LUV-0-2501-0000", @" Laser diode status ",
    @"111-LUV-0-2501-0001", @" Laser diode standby ON-OFF status ",
    @"111-LUV-0-2501-0002", @" Laser Trigger Mode Int/Ext ",
    @"111-CPS-0-2502-0000", @"ulser status ",
    @"111-RTY-0-2102-0004", @"LDLS Temperature Controller ON-OFF? ",
    @"-", @"Reserved",
    @"-", @"Reserved",
    @"-", @"Reserved",
    @"-", @"Reserved",
    @"-", @"Reserved",
    @"-", @"Reserved",
    @"111-RTY-0-2102-0000", @"LDLS Temperature Controller Temperature ",
    @"111-RTY-0-2102-0001", @"LDLS Temperature Controller Voltage ",
    @"111-RTY-0-2102-0002", @"LDLS Temperature Controller Current ",
    @"111-RTY-0-2102-0003", @"LDLS Temperature Controller Status ",
    @"111-LFI-0-2103-0000", @"Monochromator Wavelegth ",
    @"111-LFI-0-2103-0001", @"Monochromator Entrance Slit Width ",
    @"111-LFI-0-2103-0002", @"Monochromator Exit Slit Width ",
    @"111-LFI-0-2103-0003", @"Monochromator Status ",
    @"111-REI-0-2401-0000", @"Beam Monitor Amplifier Overload ",
    @"111-REU-0-2402-0000", @"Beam Monitor Readout ",
    @"111-RTY-0-2403-0000", @"Beam Monitor Temperature ",
    @"111-RTY-0-2403-0001", @"Beam Monitor Reserved  ",
    @"111-RTY-0-2403-0002", @"Beam Monitor Reserved  ",
    @"111-RTY-0-2403-0003", @"Beam Monitor Reserved  ",
    @"111-LUV-0-2501-0003", @" Laser Pulse Frequency ",
    @"111-LUV-0-2501-0004", @" Laser diode operating current ",
    @"111-LUV-0-2501-0005", @" Laser SHG crystal temperature ",
    @"111-LUV-0-2501-0006", @" Laser FHG crystal temperature ",
    @"111-LUV-0-2501-0007", @" Laser diode 1 temperature ",
    @"111-CPS-0-2502-0001", @"ulser frequency ",
    @"111-CPS-0-2502-0002", @"ulser amplitude ",
    @"111-CPS-0-2502-0003", @"ulser pulse length ",
    @"111-AAI-0-3101-0000", @"Linear Screw Drive position ",
    @"111-AAI-0-3101-0001", @"Linear Screw Drive status ",
    @"111-AAI-0-3101-0002", @"Egun plate angle ",
    @"111-RTP-0-1300-0000", @"Stahl HV Temperature ",
    @"", @""
};


#define kNumToShip_DAQlab  0 //
static NSString* itemsToShip_DAQlab[kNumToShip_DAQlab*2] = {
    /*
     @"38",  @"436-EHV-0-1001-0001-U_set",
     @"39",  @"436-EHV-0-1001-0002-U_act",
     @"40",  @"436-EHV-0-1001-0003-I_max",
     @"41",  @"436-EHV-0-1001-0004-I_act",
     @"42",  @"436-EHV-0-1001-0005-U_ramp",
     @"43",  @"436-EHV-0-1001-0030-I_limited",
     @"44",  @"436-EHV-0-1001-0031-warning",
     @"45",  @"436-EHV-0-1001-0032-error",
     @"46",  @"436-EHV-0-1002-0001-U_set",
     @"47",  @"436-EHV-0-1002-0002-U_act",
     @"48",  @"436-EHV-0-1002-0003-I_max",
     @"49",  @"436-EHV-0-1002-0004-I_act",
     @"50",  @"436-EHV-0-1002-0005-U_ramp",
     @"51",  @"436-EHV-0-1002-0030-I_limited",
     @"52",  @"436-EHV-0-1002-0031-warning",
     @"53",  @"436-EHV-0-1002-0032-error",
     @"86",  @"436-EHV-0-1003-0001-U_set",
     @"87",  @"436-EHV-0-1003-0002-U_act",
     @"88",  @"436-EHV-0-1003-0003-I_max",
     @"89",  @"436-EHV-0-1003-0004-I_act",
     @"90",  @"436-EHV-0-1003-0005-U_ramp",
     @"91",  @"436-EHV-0-1003-0030-I_limited",
     @"92",  @"436-EHV-0-1003-0031-warning",
     @"93",  @"436-EHV-0-1003-0032-error",
     @"94",  @"416-EHV-0-1001-0001-U_set",
     @"95",  @"416-EHV-0-1001-0002-U_act",
     @"96",  @"416-EHV-0-1001-0003-I_max",
     @"97",  @"416-EHV-0-1001-0004-I_act",
     @"98",  @"416-EHV-0-1001-0005-U_ramp",
     @"99",  @"416-EHV-0-1001-0030-I_limited",
     @"100", @"416-EHV-0-1001-0031-warning",
     @"101", @"416-EHV-0-1001-0032-error",
     @"303", @"436-REU-0-0201-0001-U_act",
     @"304", @"436-REU-0-0201-0020-trigger_time",
     @"305", @"436-REU-0-0201-0030-meas_flag",
     @"306", @"436-REU-0-0301-0001-U_act",
     @"307", @"436-REU-0-0301-0020-trigger_time",
     @"308", @"436-REU-0-0301-0030-meas_flag",
     */
};



