//--------------------------------------------------------
// ORModBusModel
// Created by Mark  A. Howe on Tues Sept 8, 2009
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2009 University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//Washington at the Center for Experimental Nuclear Physics and 
//Astrophysics (CENPA) sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of Washington, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------
#pragma mark •••Imported Files
@class ORSerialPort;
@class ORTimeRate;
@class ORAlarm;

@interface ORModBusModel : OrcaObject
{
    @private
        NSString*       portName;
        BOOL            portWasOpen;
        ORSerialPort*   serialPort;
		int				pollTime;
        NSMutableString* buffer;
		ORTimeRate*		timeRates;
		unsigned long	timeMeasured;
		NSMutableArray* sensors;
		int				response;
		int				lastRegister;
		int				lastAddress;
		NSMutableArray*		cmdQueue;
		NSData* lastRequest;
		BOOL shipValues;
}

#pragma mark •••Initialization
- (id)   init;
- (void) dealloc;

- (void) registerNotificationObservers;
- (void) dataReceived:(NSNotification*)note;
- (void) removeSensorByNote:(NSNotification*)aNote;

#pragma mark •••Accessors
- (NSData*) lastRequest;
- (void) setLastRequest:(NSData*)aRequest;
- (ORTimeRate*)timeRate;
- (int)  pollTime;
- (void) setPollTime:(int)aPollTime;
- (ORSerialPort*) serialPort;
- (void) setSerialPort:(ORSerialPort*)aSerialPort;
- (BOOL) portWasOpen;
- (void) setPortWasOpen:(BOOL)aPortWasOpen;
- (NSString*) portName;
- (void) setPortName:(NSString*)aPortName;
- (void) openPort:(BOOL)state;
- (unsigned long) timeMeasured;
- (NSMutableArray*) sensors;
- (void) setSensors:(NSMutableArray*)someSensors;
- (void) addSensor:(id)aSensor;
- (void) removeSensor:(id)aSensor;
- (id) sensor:(int)i;
- (unsigned int) crc:(unsigned char*) buf count:(int)cnt;
- (void) serialPortWriteProgress:(NSDictionary *)dataDictionary;

- (void) readHoldingReg:(int)reg_num deviceAddress:(int) address;
- (void) writeHoldingReg:(int)reg_num deviceAddress:(int) address withValue:(int)aValue;
- (BOOL) shipValues;
- (void) setShipValues:(BOOL)aShipState;

#pragma mark •••Commands
- (void) pollSensors;

- (id)   initWithCoder:(NSCoder*)decoder;
- (void) encodeWithCoder:(NSCoder*)encoder;
@end

extern NSString* ORModBusModelPollTimeChanged;
extern NSString* ORModBusModelSerialPortChanged;
extern NSString* ORModBusLock;
extern NSString* ORModBusModelPortNameChanged;
extern NSString* ORModBusModelPortStateChanged;
extern NSString* ORModBusModelSensorsChanged;
extern NSString* ORModBusModelSensorAdded;
extern NSString* ORModBusModelSensorRemoved;
extern NSString* ORModBusModelTimeout;
extern NSString* ORModBusModelShipValues;

