//--------------------------------------------------------
// ObjWithHistoryModel
// Created by Mark  A. Howe on Fri Jul 22 2005
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2005 CENPA, University of Washington. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//Washington at the Center for Experimental Nuclear Physics and 
//Astrophysics (CENPA) sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of Washington, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files
@interface ObjWithHistoryModel : OrcaObject
{
    @private
		NSMutableArray* roiSet;
}

#pragma mark ***Initialization
- (void) dealloc;

#pragma mark ***Accessors
- (NSMutableArray*) rois:(int)index;
- (NSString*) historyName;
- (NSString*) historyPath;
- (void) saveHistory;
- (void) loadHistory;
- (void) deleteHistory;
- (id) history;
- (void) setHistory:(id)someHistory;
@end
