#!/usr/bin/expect --
set timeout -1
spawn scp  -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=1 <isDir> <verbose> <sourcePath> <userName>@<host>:<destinationPath>
expect {
  "*>* " { }
  "*$* " { }
  "*#* " { }
  "*%* " { }
  "assword:" {send "<password>\n"}
}
expect eof
catch wait result
exit [lindex $result 3]
