#!/usr/bin/expect -f

# Expect script to supply username for remote ssh server and execute command.
# Currently this assumes that valid ssh keys are exist between the host
# and the remote server.

set nargs [llength $argv]
set username [lrange $argv 0 0]
set ipaddr [lrange $argv 1 1]
set scriptname [lrange $argv 2 2]
set timeout -1

# now connect to remote UNIX box (ipaddr) with given script to execute
match_max 100000
send_user "Connecting to flashcam with user $username on $ipaddr\n"
spawn -noecho ssh -X $username@$ipaddr

expect {
    "*>* " { }
    "*$* " { }
    "*#* " { }
    "*%* " { }
    "assword:" {
        send_user "SSH keys not valid for user $username on $ipaddr\n"
        exit 1
    }
    default {
        send_user "Login to $ipaddr failed\n"
        exit 1
    }
}

send "$scriptname [lrange $argv 3 $nargs-1]\r"
expect {
    "0" {
        send_user "No flashcam run in progress on $ipaddr\n"
    }
    "1" {
        send_user "Killed readout-fc process on $ipaddr\n"
    }
    default {
        send_user "Killed readout-fc processes on $ipaddr\n"
    }
}
send "exit\n\r"
expect eof
