#!/usr/bin/expect -f

# Expect script to supply username for remote ssh server and execute command.
# Currently this assumes that valid ssh keys are exist between the host
# and the remote server.

set nargs [llength $argv]
set username [lrange $argv 0 0]
set ipaddr [lrange $argv 1 1]
set script [lrange $argv 2 2]
set scriptname [regsub -all {\{|\}} $script ""]
set larg [lrange $argv $nargs-2 $nargs-2]
set run [lrange $argv $nargs-1 $nargs-1]
set args [regsub -all {\{|\}} [lrange $argv 3 $nargs-1] ""]
set timeout -1

# now connect to remote UNIX box (ipaddr) with given script to execute
match_max 100000
send_user "Attempting to start flashcam run $run with user $username on $ipaddr\n"
spawn -noecho ssh -X -q $username@$ipaddr

expect {
    "*>* " { }
    "*$* " { }
    "*#* " { }
    "*%* " { }
    "assword:" {
        send_user "SSH keys not valid for user $username on $ipaddr\n"
        exit 1
    }
    default {
        send_user "Login to $ipaddr failed\n"
        exit 1
    }
}

send "cd \$FLASHCAMDIR/server; ./efbprun $scriptname $args\r"
expect {
    "EfbpSearchDevice: found device address" {
        #send_user "ORFlashCamCard: found device 0x$larg endl "
        send "exit\r"
    }
    "EfbpSearchDevice: can not find address" {
        send_user "ORFlashCamCard: cannot find device at addres 0x$larg endl "
        send "exit\r"
    }
    "ERROR: can not init Efbp devices" {
        send_user "ORFlashCamCard: cannot init interface at address 0x$larg endl "
        send "exit\r"
    }
    "ERROR: can not init interface" {
        send_user "ORFlashCamCard: cannot init interface at address 0xlarg endl "
        send "exit\r"
    }
    "starting readout-fc250b" {
        send_user "ORFlashCamRunModel: starting readout, writing to $run endl "
        exp_continue
    }
    "OK/running" {
        send_user "$run $expect_out(buffer)"
        exp_continue
    }
    "OK/terminated" {
        send_user "Completed flashcam run $run\n"
    }
    "Killed" {
        send_user "Flashcam process for run $run killed\n"
    }
    "Terminated" {
        send_user "Flashcam process for run $run terminated\n"
    }
    "Error can not contact output stream" {
        send_user "Cannot write to user specified remote host location\n"
    }
    "Error can not initialize adc system" {
        send_user "Failed to connect to flashcam card on $ipaddr, check ethernet settings and connections\n"
    }
    "no adc/trigger cards ..." {
        send_user "No flashcam cards found, check ethernet type and board address\n"
    }
    "Error invalid option on command line" {
        send_user "Invalid command line option\n"
    }
    "must stop" {
        send_user "Run stopped due to errors\n"
    }
    eof {
        send_user "Failed to start flashcam readout for run $run\n"
        exp_continue
    }
}
send_user "terminating expect script\n"
send "exit\n\r"
expect eof
