//--------------------------------------------------------
// ORAcqirisDC440Model
// Created by Mark A. Howe on Fri Jun 22 2007
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2007 CENPA, University of Washington. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//Washington at the Center for Experimental Nuclear Physics and 
//Astrophysics (CENPA) sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of Washington, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ¥¥¥Imported Files

#import <Cocoa/Cocoa.h>
#import "ORcPCIIOCard.h"
#import "ORDataTaker.h"
#import "SBC_Config.h"
#import "SBC_Cmds.h"
#import "ORHWWizard.h"
#import "AcqirisDC440Cmds.h"

#pragma mark ¥¥¥Forward Declarations
@class ORRateGroup;

@interface ORAcqirisDC440Model : ORcPCIIOCard <ORDataTaker,ORHWWizard>
{	
    unsigned long	dataId;
	unsigned long	numberSamples;
	double			delayTime;
	double			sampleInterval;
    int				fullScale;
    double			verticalOffset;
    int				coupling;
    int				triggerSource;
    int				triggerCoupling;
    NSMutableArray*		triggerLevels;
    int				triggerSlope;
	unsigned long	boardID;
	int				lengthBuffer[2];
	short			tempBuffer[2][20000];
	BOOL			firstTime;
	ORRateGroup*	sampleRateGroup;
	unsigned long 	sampleCount[2];
	BOOL			isRunning;
	BOOL			samplingWaveforms;
	//some cache space
	unsigned long   location;
	SBC_Packet readDataPacket;
	SBC_Packet returnPacket;
    BOOL readContinously;
    unsigned short enableMask;
}

- (id) init;
- (void) dealloc;
- (void) setUpImage;
- (void) makeMainController;


#pragma mark ¥¥¥Accessors
- (void) setEnableMaskBit:(int)bit withValue:(BOOL)aValue;
- (unsigned short) enableMask;
- (void) setEnableMask:(unsigned short)aEnableMask;
- (BOOL) readContinously;
- (void) setReadContinously:(BOOL)aReadContinously;
- (int) triggerSlope;
- (void) setTriggerSlope:(int)aTriggerSlope;
- (double) triggerLevel:(int)index;
- (void) setTriggerLevel:(int)index withValue:(double)aTriggerLevel;
- (int) triggerCoupling;
- (void) setTriggerCoupling:(int)aTriggerCoupling;
- (int) triggerSource;
- (void) setTriggerSource:(int)aTriggerSource;
- (int) coupling;
- (void) setCoupling:(int)aCoupling;
- (double) verticalOffset;
- (void) setVerticalOffset:(double)aOffset;
- (void) setFullScaleFromValue:(double)aFullScale;
- (int) fullScale;
- (void) setFullScale:(int)aFullScale;
- (double) delayTime;
- (void) setDelayTime:(double)aDelayTime;
- (double) sampleInterval;
- (void) setSampleInterval:(double)aSampleInterval;
- (double) sampleInterval;
- (unsigned long) numberSamples;
- (void) setNumberSamples:(unsigned long)aNumberSamples;
- (unsigned long) probe:(BOOL) verbose;
- (void) assignBoardID;
- (int) boardID;
- (unsigned long) dataId;
- (void) setDataId: (unsigned long) DataId;
- (BOOL) samplingWaveforms;
- (void) setSamplingWaveforms:(BOOL)state;

#pragma mark ¥¥¥Rate
- (unsigned long) getCounter:(int)tag forGroup:(int)groupTag;
- (id) rateObject:(int)channel;
- (ORRateGroup*)    sampleRateGroup;
- (void)			setSampleRateGroup:(ORRateGroup*)newSampleRateGroup;
- (void) startRates;
- (void) clearSampleCounts;
- (BOOL) bumpRateFromDecodeStage:(short)chan;

- (void) initBoard;
- (void) loadDialog;

- (unsigned long) setConfigureHorizontal;
- (unsigned long) setConfigureVertical:(int)chan;
- (unsigned long) setConfigureTrigSource;
- (unsigned long) setConfigureMemory;
- (unsigned long) setConfigureTrigClass;
- (unsigned long) getHorizontal;
- (unsigned long) getVertical;
- (unsigned long) getMemory;
- (unsigned long) getNumberChannels;
- (unsigned long) getTriggerSource;
- (void)		  getOneWaveform;
- (void)		  getOneWaveform:(BOOL)state;
- (unsigned long) getTriggerClass;
- (void) reportAll;
- (unsigned long) reportTriggerSource;
- (unsigned long) reportHorizontal;
- (unsigned long) reportVertical;
- (unsigned long) reportMemory;
- (unsigned long) reportTriggerClass;
- (id) decodeError:(long)status;

- (Acquiris_GetCmdStatusStruct) doGetXXXCommand:(unsigned long)aCmdNumber cmdArgs:(NSString*)args;
- (long) doSetXXXCommand:(unsigned long)aCmdNumber cmdArgs:(NSString*)args;
- (long) doCommand:(unsigned long)aCmdNumber cmdArgs:(NSString*)args;

- (int) lengthBuffer:(int)set;
- (float) buffer:(int)x set:(int)i;

#pragma mark ¥¥¥DataTaker
- (int) load_HW_Config_Structure:(SBC_crate_config*)configStruct index:(int)index;
- (NSDictionary*) dataRecordDescription;
- (void) runTaskStarted:(ORDataPacket*)aDataPacket userInfo:(NSDictionary*)userInfo;
- (void) takeData:(ORDataPacket*)aDataPacket userInfo:(NSDictionary*)userInfo;
- (void) runTaskStopped:(ORDataPacket*)aDataPacket userInfo:(NSDictionary*)userInfo;
- (void) setDataIds:(id)assigner;
- (void) syncDataIdsWith:(id)anotherCard;

#pragma mark ¥¥¥Archival
- (id) initWithCoder:(NSCoder*)decoder;
- (void) encodeWithCoder:(NSCoder*)encoder;

#pragma mark ¥¥¥HW Wizard
- (NSArray*) wizardSelections;
- (NSArray*) wizardParameters;
- (int) numberOfChannels;

@end

extern NSString* ORAcqirisDC440ModelEnableMaskChanged;
extern NSString* ORAcqirisDC440RateGroupChangedNotification;
extern NSString* ORAcqirisDC440ReadContinouslyChanged;
extern NSString* ORAcqirisDC440TriggerSlopeChanged;
extern NSString* ORAcqirisDC440TriggerLevelChanged;
extern NSString* ORAcqirisDC440TriggerCouplingChanged;
extern NSString* ORAcqirisDC440TriggerSourceChanged;
extern NSString* ORAcqirisDC440CouplingChanged;
extern NSString* ORAcqirisDC440VerticalOffsetChanged;
extern NSString* ORAcqirisDC440FullScaleChanged;
extern NSString* ORAcqirisDC440DelayTimeChanged;
extern NSString* ORAcqirisDC440DelayTimeChanged;
extern NSString* ORAcqirisDC440SampleIntervalChanged;
extern NSString* ORAcqirisDC440NumberSamplesChanged;
extern NSString* ORAcqirisDC440DataChanged;
extern NSString* ORAcqirisDC440SettingsLock;
extern NSString* ORAcqirisDC440SamplingWaveforms;
extern NSString* ORAcqirisDC440BoardIDChanged;

