//--------------------------------------------------------
// ORTDC3377Model
// Created by Mark  A. Howe on Tue Aug 02 2005
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2005 CENPA, University of Washington. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//Washington at the Center for Experimental Nuclear Physics and 
//Astrophysics (CENPA) sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of Washington, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files


#import "ORCamacIOCard.h"
#import "ORHWWizard.h"
#import "ORDataTaker.h"

@class ORTestSuit;

#define kNum3377TDCTests 3

@interface ORTDC3377Model : ORCamacIOCard <ORDataTaker,ORHWWizard,ORHWRamping>
{
    @private
        uint32_t   dataId;
        BOOL            firstTime;
        
        //place to cache some stuff for alittle more speed.
        uint32_t 	unChangingDataPart;
        int cachedStation;
		int controlMode;
		unsigned short controlReg0;
		unsigned short controlReg1;
		unsigned short controlReg2;
		unsigned short controlReg3;
		unsigned short controlReg4;
		unsigned short controlReg5;

		//contents of the above registers
		BOOL bothEdges;
		BOOL feraMode;
		BOOL multiEventBufferMode;
		BOOL skipHeader;
		BOOL fastFeraMode;
		BOOL testEnabled;
		unsigned short pulseWidth;
		unsigned short pulseDelay;
		unsigned short clockUnit;
		unsigned short pauseInterval;
		unsigned short maxHitsPerTDC;
		unsigned short maxFullScaleTime;
		unsigned short requestDelay;
		unsigned short dataOffset;
		unsigned short timeOut;
		unsigned short testClock;
		unsigned short pulsesToGenerate;
		unsigned short dataShift;
		NSMutableArray* testingStatus;
		NSMutableArray* testingEnabled;
		BOOL testsRunning;
		ORTestSuit* testSuit;
}   

#pragma mark ***Initialization
- (id)   init;
- (void) dealloc;

#pragma mark ***Accessors
- (BOOL) testsRunning;
- (void) setTestsRunning:(BOOL)aTestsRunning;
- (NSMutableArray*) testingEnabled;
- (void) setTestingEnabled:(NSMutableArray*)aTestEnabled;
- (BOOL) testingIsEnabled:(int)index;
- (NSMutableArray*) testingStatus;
- (void) setTestingStatus:(NSMutableArray*)aTestingStatus;
- (NSString*) testingStatus:(int)index;
- (BOOL) testingEnabled:(int)index;
- (unsigned short) dataShift;
- (void) setDataShift:(unsigned short)aDataShift;
- (unsigned short) pulsesToGenerate;
- (void) setPulsesToGenerate:(unsigned short)aPulsesToGenerate;
- (unsigned short) testClock;
- (void) setTestClock:(unsigned short)aTestClock;
- (BOOL) testEnabled;
- (void) setTestEnabled:(BOOL)aTestEnabled;
- (unsigned short) timeOut;
- (void) setTimeOut:(unsigned short)aTimeout;
- (unsigned short) dataOffset;
- (void) setDataOffset:(unsigned short)aOffset;
- (unsigned short) requestDelay;
- (void) setRequestDelay:(unsigned short)aRequestDelay;
- (unsigned short) maxFullScaleTime;
- (void) setMaxFullScaleTime:(unsigned short)aMaxFullScaleTime;
- (unsigned short) maxHitsPerTDC;
- (void) setMaxHitsPerTDC:(unsigned short)aMaxHitsPerTDC;
- (BOOL) fastFeraMode;
- (void) setFastFeraMode:(BOOL)aFastFeraMode;
- (unsigned short) pauseInterval;
- (void) setPauseInterval:(unsigned short)aPauseInterval;
- (unsigned short) clockUnit;
- (void) setClockUnit:(unsigned short)aClockUnit;
- (unsigned short) pulseDelay;
- (void) setPulseDelay:(unsigned short)aPulseDelay;
- (unsigned short) pulseWidth;
- (void) setPulseWidth:(unsigned short)aPulseWidth;
- (BOOL) skipHeader;
- (void) setSkipHeader:(BOOL)aSkipHeader;
- (BOOL) multiEventBufferMode;
- (void) setMultiEventBufferMode:(BOOL)aMultiEventBufferMode;
- (BOOL) feraMode;
- (void) setFeraMode:(BOOL)aFeraMode;
- (BOOL) bothEdges;
- (void) setBothEdges:(BOOL)aBothEdges;
- (unsigned short) controlReg5;
- (void) setControlReg5:(unsigned short)aControlReg5;
- (unsigned short) controlReg4;
- (void) setControlReg4:(unsigned short)aControlReg4;
- (unsigned short) controlReg3;
- (void) setControlReg3:(unsigned short)aControlReg3;
- (unsigned short) controlReg2;
- (void) setControlReg2:(unsigned short)aControlReg2;
- (unsigned short) controlReg1;
- (void) setControlReg1:(unsigned short)aControlReg1;
- (unsigned short) controlReg0;
- (void) setControlReg0:(unsigned short)aControlReg0;
- (int) controlMode;
- (void) setControlMode:(int)aControlMode;
- (uint32_t) dataId;
- (void) setDataId: (uint32_t) DataId;

#pragma mark ¥¥¥HW Wizard
- (NSArray*) wizardSelections;
- (NSArray*) wizardParameters;
- (int) numberOfChannels;

#pragma mark ¥¥¥DataTaker
- (NSDictionary*) dataRecordDescription;
- (void) appendDataDescription:(ORDataPacket*)aDataPacket userInfo:(NSDictionary*)userInfo;
- (void) setDataIds:(id)assigner;
- (void) syncDataIdsWith:(id)anotherCard;
- (void) runTaskStarted:(ORDataPacket*)aDataPacket userInfo:(NSDictionary*)userInfo;
- (void) takeData:(ORDataPacket*)aDataPacket userInfo:(NSDictionary*)userInfo;
- (void) shipEvent:(ORDataPacket*)aDataPacket data:(NSMutableData*)eventBuffer numWords:(NSUInteger)dataWordCount;
- (void) runTaskStopped:(ORDataPacket*)aDataPacket userInfo:(NSDictionary*)userInfo;
- (void) reset;

#pragma mark ¥¥¥Hardware Access
- (BOOL) loadTheMode;
- (void) loadRegisters;
- (void) formatRegisters;
- (void) readBackRegisters:(BOOL)check;
- (void) checkEvent;
- (void) enableAcq;
- (void) runTests;
- (void) runningTest:(int)index status:(NSString*)theStatus;
- (void) loadRegisters:(BOOL)verbose;

@end

extern NSString* ORTDC3377ModelTestsRunningChanged;
extern NSString* ORTDC3377ModelTestingEnabledChanged;
extern NSString* ORTDC3377ModelTestingStatusChanged;
extern NSString* ORTDC3377ModelDataShiftChanged;
extern NSString* ORTDC3377ModelPulsesToGenerateChanged;
extern NSString* ORTDC3377ModelTestClockChanged;
extern NSString* ORTDC3377ModelTestEnabledChanged;
extern NSString* ORTDC3377ModelTimeoutChanged;
extern NSString* ORTDC3377ModelDataOffsetChanged;
extern NSString* ORTDC3377ModelRequestDelayChanged;
extern NSString* ORTDC3377ModelMaxFullScaleTimeChanged;
extern NSString* ORTDC3377ModelMaxHitsPerTDCChanged;
extern NSString* ORTDC3377ModelFastFeraModeChanged;
extern NSString* ORTDC3377ModelPauseIntervalChanged;
extern NSString* ORTDC3377ModelClockUnitChanged;
extern NSString* ORTDC3377ModelPulseDelayChanged;
extern NSString* ORTDC3377ModelPulseWidthChanged;
extern NSString* ORTDC3377ModelSkipHeaderChanged;
extern NSString* ORTDC3377ModelMultiEventBufferModeChanged;
extern NSString* ORTDC3377ModelFeraModeChanged;
extern NSString* ORTDC3377ModelBothEdgesChanged;
extern NSString* ORTDC3377ModelControlReg5Changed;
extern NSString* ORTDC3377ModelControlReg4Changed;
extern NSString* ORTDC3377ModelControlReg3Changed;
extern NSString* ORTDC3377ModelControlReg2Changed;
extern NSString* ORTDC3377ModelControlReg1Changed;
extern NSString* ORTDC3377ModelControlReg0Changed;
extern NSString* ORTDC3377ModelRunModeChanged;
extern NSString* ORTDC3377SettingsLock;


