//--------------------------------------------------------
// ORPDcuController
// Created by Mark  A. Howe on Wed 4/15/2009
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2009 CENPA, University of Washington. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//Washington at the Center for Experimental Nuclear Physics and 
//Astrophysics (CENPA) sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of Washington, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the us of this software.
//-------------------------------------------------------------

#pragma mark •••Imported Files

@interface ORSerialPortController : NSObject
{
    IBOutlet NSTextField*	portStateField;
    IBOutlet NSButton*		openPortButton;
    IBOutlet NSPopUpButton*	portListPopup;
    IBOutlet NSView*		portControlsContent;
	IBOutlet NSBox*			portControlsView;
	IBOutlet id				owner;
    NSArray*                topLevelObjects;
}

#pragma mark •••Initialization
- (void) awakeFromNib;

#pragma mark •••Notifications
- (void) registerNotificationObservers;
- (void) updateWindow;
- (void) updateButtons:(BOOL)locked;
- (BOOL) portLocked;

#pragma mark •••Interface Management
- (void) popupIsAboutToOpen:(NSNotification*)aNote;
- (void) portNameChanged:(NSNotification*)aNote;
- (void) portStateChanged:(NSNotification*)aNote;
- (void) updatePortList:(NSNotification*)aNote;
- (void) popupIsAboutToOpen:(NSNotification*)aNote;

#pragma mark •••Actions
- (IBAction) portListAction:(id) sender;
- (IBAction) openPortAction:(id)sender;

@end


